// Mozzi Node Definitions - FILTER CATEGORY
// Generated by MozziFlow Intelligent Agent

NodeLibrary.push({
    nodetype: 'filter/mozzi_audiodelay',
    help: {
    "summary": "Simple digital audio delay line (Echo).",
    "inlets": {
        "in": "Audio signal input.",
        "time": "Delay length in milliseconds (ms)."
    },
    "outlets": {
        "out": "The delayed version of the input signal."
    },
    "usage": "Create 'doubling' effects, spatial thickening, or very short rhythmic offsets. Note: This version has a fixed internal buffer size; longer times may require higher memory settings."
},
    nodeclass: "MozziAudioDelay",
    description: "Simple audio delay.",
    mozzi: {
        rate: "audio",
        includes: ["#include <AudioDelay.h>"],
        defaults: {"in":"0","time":"500"},
        global: function(n,v){ return "AudioDelay<1024, int> "+v+";"; },
        audio: function(n,v,i){ return v+"_out = "+v+".next((int)"+i.in+", (uint16_t)"+i.time+");"; },
    },
    rpdnode: {
    "title": "Audio Delay",
    "inlets": {
        "in": {
            "type": "mozziflow/string",
            "no_text": true,
            "color": "bipolar_8"
        },
        "time": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "unipolar_16" // ms can be large
        }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "bipolar_8"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'filter/mozzi_lpf',
    help: {
    "summary": "Standard 1st-order Low Pass Filter (LPF).",
    "inlets": {
        "in": "Audio signal to filter.",
        "cutoff": "Frequency threshold (0-255). Lower values remove more high frequencies."
    },
    "outlets": {
        "out": "Smooth, 'warm' audio signal."
    },
    "usage": "The simplest way to remove harshness from a digital oscillator or to simulate distance by 'muffling' the sound."
},
    nodeclass: "MozziLPF",
    description: "Standard LPF.",
    mozzi: {
        rate: "audio",
        includes: ["#include <ResonantFilter.h>"],
        defaults: {"in":"0","cutoff":"128"},
        global: function(n,v){ return "LowPassFilter "+v+";"; },
        control: function(n,v,i){ return v+".setCutoffFreq((uint8_t)"+i.cutoff+");"; },
        audio: function(n,v,i){ return v+"_out = "+v+".next((int)"+i.in+");"; },
    },
    rpdnode: {
    "title": "LowPass",
    "inlets": {
        "in": {
            "type": "mozziflow/string",
            "no_text": true,
            "color": "bipolar_8"
        },
        "cutoff": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "unipolar_8" // LPF uses 0-255? setCutoffFreq usually 0-255
        }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "bipolar_8"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'filter/mozzi_svf',
    help: {
    "summary": "High-quality State Variable Filter (SVF).",
    "inlets": {
        "in": "Audio signal input.",
        "cutoff": "Centre Frequency (20 - 4096 Hz).",
        "res": "Resonance (0-255). 0 = Maximum Resonance, 255 = No Resonance."
    },
    "outlets": {
        "out": "Filtered audio signal."
    },
    "usage": "Standard filter for synthesis. NOTE: Resonance is inverted - 0 is the sharpest setting!"
},
    nodeclass: "MozziSVF",
    description: "Multi-mode Resonant Filter.",
    mozzi: { 
        rate: 'audio', 
        includes: ["#include <StateVariable.h>"], 
        defaults: { in: "0", cutoff: "1200", res: "200" }, 
        global: function(n,v){ 
            var mode = (n.data && n.data.mode) ? n.data.mode : "LOWPASS";
            return "StateVariable<" + mode + "> " + v + ";"; 
        }, 
        control: function(n,v,i){ 
            return v+".setCentreFreq((int)"+i.cutoff+");\n\t"+v+".setResonance((uint8_t)"+i.res+");"; 
        },
        audio: function(n,v,i){ return v+"_out = "+v+".next((int)"+i.in+");"; } 
    },
    renderer: {
        'html': function(bodyElm, node) {
            if (!node.data) node.data = { mode: "LOWPASS" };
            var container = document.createElement('div');
            container.style.padding = "5px"; container.style.textAlign = "center";
            
            var select = document.createElement('select');
            select.className = "mozzi-buffer-select"; 
            ["LOWPASS", "BANDPASS", "HIGHPASS", "NOTCH"].forEach(function(m) {
                var opt = document.createElement('option');
                opt.value = m; opt.innerText = m;
                if (m === node.data.mode) opt.selected = true;
                select.appendChild(opt);
            });
            select.onchange = function() { node.data.mode = this.value; };
            container.appendChild(select);
            bodyElm.appendChild(container);
        }
    },
    rpdnode: {
    "title": "SVF Filter",
    "inlets": {
        "in": {
            "type": "mozziflow/string",
            "no_text": true,
            "color": "bipolar_8"
        },
        "cutoff": {
            "type": "mozziflow/string",
            "label": "Freq (20-4k)",
            "is_control": true,
            "color": "unipolar_16"
        },
        "res": {
            "type": "mozziflow/string",
            "label": "Res (Inv 0-255)",
            "is_control": true,
            "color": "unipolar_8"
        }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "bipolar_8"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'filter/mozzi_res',
    help: {
    "summary": "High-Q Resonant Filter optimized for sharp frequency peaks.",
    "inlets": {
        "in": "Audio signal input.",
        "cutoff": "Filter frequency.",
        "res": "Resonance intensity."
    },
    "outlets": {
        "out": "Resonant filtered audio."
    },
    "usage": "Ideal for 'Vocal' filtering (Formant synthesis) or creating aggressive, whistling 'Acid' sounds. It focuses specifically on the frequency peak."
},
    nodeclass: "MozziRes",
    description: "Resonant LPF.",
    mozzi: {
        rate: "audio",
        includes: ["#include <ResonantFilter.h>"],
        defaults: {"in":"0","cutoff":"128","res":"128"},
        global: function(n,v){ return "ResonantFilter<LOWPASS, uint8_t> "+v+";"; },
        control: function(n,v,i){ return v+".setCutoffFreqAndResonance((uint8_t)"+i.cutoff+", (uint8_t)"+i.res+");"; },
        audio: function(n,v,i){ return v+"_out = "+v+".next((int)"+i.in+");"; },
    },
    rpdnode: {
    "title": "Resonant LP",
    "inlets": {
        "in": {
            "type": "mozziflow/string",
            "no_text": true,
            "color": "bipolar_8"
        },
        "cutoff": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "unipolar_8" // ResonantFilter usually 0-255 cutoff
        },
        "res": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "unipolar_8"
        }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "bipolar_8"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'filter/mozzi_waveshaper',
    help: {
    "summary": "Non-linear Waveshaping Distortion using lookup tables.",
    "inlets": {
        "in": "Audio signal input."
    },
    "outlets": {
        "out": "Distorted/Saturated audio signal."
    },
    "usage": "Adds digital 'grit,' 'warmth,' or harmonic complexity. It remaps the input amplitudes to new values, allowing you to transform a simple sine wave into a rich, overdriven wave."
},
    nodeclass: "MozziWaveShaper",
    description: "Wave shaping distortion.",
    mozzi: {
        rate: "audio",
        includes: ["#include <WaveShaper.h>","#include <tables/waveshape_chebyshev_3rd_256_int8.h>"],
        defaults: {"in":"0"},
        global: function(n,v){ return "WaveShaper<char> "+v+"(CHEBYSHEV_3RD_256_DATA);"; },
        audio: function(n,v,i){ return v+"_out = "+v+".next((int)"+i.in+");"; },
        inlet_rates: {"in":"audio"},
    },
    rpdnode: {
    "title": "WaveShaper",
    "inlets": {
        "in": {
            "type": "mozziflow/string",
            "no_text": true,
            "color": "bipolar_8"
        }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "bipolar_8"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'filter/mozzi_wavefolder',
    help: {
    "summary": "Classic 'West Coast' Wavefolder. Folds signal peaks back onto themselves.",
    "inlets": {
        "in": "Signal input.",
        "low": "Lower folding limit (e.g., -128).",
        "high": "Upper folding limit (e.g., 127)."
    },
    "outlets": {
        "out": "Folded signal result."
    },
    "usage": "Use different absolute values for 'low' and 'high' to create asymmetric folding, which generates even harmonics. Works best with Sine/Triangle waves."
},
    nodeclass: "MozziWaveFolder",
    description: "Asymmetric folding distortion.",
    mozzi: {
        rate: "audio",
        includes: ["#include <WaveFolder.h>"],
        defaults: {"in":"0","low":"-128","high":"127"},
        global: function(n,v){ return "WaveFolder<int> "+v+";"; },
        control: function(n,v,i){ return v+".setLimits((int)"+i.low+", (int)"+i.high+");"; },
        audio: function(n,v,i){ return v+"_out = "+v+".next((int)"+i.in+");"; },
    },
    rpdnode: {
    "title": "WaveFolder",
    "inlets": {
        "in": {
            "type": "mozziflow/string",
            "no_text": true
        },
        "low": {
            "type": "mozziflow/string",
            "is_control": true
        },
        "high": {
            "type": "mozziflow/string",
            "is_control": true
        }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'filter/mozzi_dcfilter',
    help: {
    "summary": "Removes constant DC Bias (offset) from an audio signal.",
    "inlets": {
        "in": "Audio signal input."
    },
    "outlets": {
        "out": "Zero-centered audio signal."
    },
    "usage": "Essential safety node. Use this at the end of your signal chain to ensure the audio is balanced around 0V. This prevents loud clicks, pops, and potential damage to your speakers."
},
        nodeclass: "MozziDCFilter",
        description: "Removes DC offset.",
        mozzi: {
            rate: "audio",
            includes: ["#include <DCfilter.h>"],
            defaults: {"in":"0"},
            global: function(n,v){ return "DCfilter " + v + "(0.99f);"; },
            audio: function(n,v,i){ return v+"_out = "+v+".next((int)"+i.in+");"; },
        },
    rpdnode: {
    "title": "DC Filter",
    "inlets": {
        "in": {
            "type": "mozziflow/string",
            "no_text": true
        }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'filter/mozzi_oversample',
    help: {
    "summary": "2x Oversampling filter to reduce digital aliasing noise.",
    "inlets": {
        "in": "Audio signal input."
    },
    "outlets": {
        "out": "Cleaner, higher-quality audio."
    },
    "usage": "Digital synthesis often produces 'aliasing' (phantom frequencies) at high pitches. Use the dropdown to select resolution increase. Higher bits = cleaner sound but more lag."
},
    nodeclass: "MozziOverSample",
    description: "Anti-aliasing filter.",
    mozzi: {
        rate: "audio",
        includes: ["#include <OverSample.h>"],
        defaults: {"in":"0"},
        global: function(n,v){ 
            var bits = (n.data && n.data.resolution) ? n.data.resolution : "2";
            return "OverSample<int, " + bits + "> "+v+";"; 
        },
        audio: function(n,v,i){ return v+"_out = "+v+".next((int)"+i.in+");"; },
        inlet_rates: {"in":"audio"},
    },
    renderer: {
        'html': function(bodyElm, node) {
            if (!node.data) node.data = { resolution: "2" };
            var container = document.createElement('div');
            container.style.padding = "5px"; container.style.textAlign = "center";
            
            var label = document.createElement('div');
            label.innerText = "Resolution (Bits):";
            label.style.fontSize = "9px"; label.style.marginBottom = "3px";
            
            var select = document.createElement('select');
            select.className = "mozzi-buffer-select"; 
            [1, 2, 3, 4].forEach(function(b) {
                var opt = document.createElement('option');
                opt.value = b.toString(); 
                opt.innerText = "+" + b + " bits";
                if (b.toString() === node.data.resolution) opt.selected = true;
                select.appendChild(opt);
            });
            
            select.onchange = function() { node.data.resolution = this.value; };
            
            container.appendChild(label);
            container.appendChild(select);
            bodyElm.appendChild(container);
        }
    },
    rpdnode: {
    "title": "OverSample",
    "inlets": {
        "in": {
            "type": "mozziflow/string",
            "no_text": true,
            "color": "bipolar_8"
        },
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "bipolar_8"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'filter/mozzi_delay_fb',
    help: {
    "summary": "Professional Digital Delay with Feedback and variable buffer size.",
    "inlets": {
        "in": "Audio input signal.",
        "samples": "Delay time in samples. (At 16384Hz, 1638 samples = 100ms).",
        "feedback": "Repetition intensity (0-255, mapped to -128/127)."
    },
    "outlets": {
        "out": "Delayed signal with repetitions."
    },
    "usage": "Use dropdowns to set buffer size, interpolation (LINEAR for sweeps, ALLPASS for reverb) and data type (int8 saves 50% RAM). Warning: Buffer size must be a power of 2."
},
    nodeclass: "MozziDelayFB",
    description: "Configurable Delay with Feedback.",
    mozzi: {
        rate: "audio",
        includes: ["#include <mozzi_fixmath.h>","#include <AudioDelayFeedback.h>"],
        defaults: {"in":"0","samples":"512","feedback":"128"},
        global: function(n, v) { 
            var size = (n.data && n.data.bufferSize) ? n.data.bufferSize : 512;
            var interp = (n.data && n.data.interp) ? n.data.interp : "LINEAR";
            var type = (n.data && n.data.type) ? n.data.type : "int";
            return "AudioDelayFeedback<" + size + ", " + interp + ", " + type + "> " + v + ";"; 
        },
        control: function(n, v, i) { 
            return v + ".setFeedbackLevel((int8_t)((int)" + i.feedback + " - 128));\n\t" +
                   v + ".setDelayTimeCells((uint16_t)" + i.samples + ");";
        },
        audio: function(n, v, i) { 
            return v + "_out = " + v + ".next((int)" + i.in + ");"; 
        },
        inlet_rates: {"in":"audio","samples":"control","feedback":"control"},
    },
    renderer: {
        'html': function(bodyElm, node) {
            if (!node.data) node.data = { bufferSize: 512, interp: "LINEAR", type: "int" };
            var container = document.createElement('div');
            container.style.padding = "5px"; container.style.textAlign = "center";
            
            var addSelect = function(labelTxt, key, options) {
                var l = document.createElement('div');
                l.innerText = labelTxt; l.style.fontSize = "8px"; l.style.color = "#888";
                var s = document.createElement('select');
                s.className = "mozzi-buffer-select"; s.style.width = "100%";
                options.forEach(function(o) {
                    var opt = document.createElement('option');
                    opt.value = o; opt.innerText = o;
                    if (o == node.data[key]) opt.selected = true;
                    s.appendChild(opt);
                });
                s.onchange = function() { node.data[key] = this.value; };
                container.appendChild(l); container.appendChild(s);
            };

            addSelect("Buffer Size:", "bufferSize", [128, 256, 512, 1024, 2048, 4096]);
            addSelect("Interp:", "interp", ["LINEAR", "ALLPASS"]);
            addSelect("Type:", "type", ["int", "int8_t"]);
            
            bodyElm.appendChild(container);
        }
    },
    rpdnode: {
    "title": "Delay FB",
    "inlets": {
        "in": {
            "type": "mozziflow/string",
            "no_text": true,
            "color": "bipolar_8"
        },
        "samples": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "unipolar_16" // Delay time in samples
        },
        "feedback": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "unipolar_8"
        }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "bipolar_8"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'filter/mozzi_reverb',
    help: {
    "summary": "Schroeder-style Reverb Tank simulator with adjustable reflections and loop times.",
    "inlets": {
        "in": "Audio signal input.",
        "mix": "Dry/Wet balance (0 = Clean, 255 = Full Effect).",
        "room": "Feedback level / Room size (0-255, mapped to -128/127).",
        "e1-e3": "Early reflection times (0-127).",
        "l1-l2": "Loop recirculating times (0-255)."
    },
    "outlets": {
        "out": "Processed audio signal."
    },
    "usage": "Use 'room' for decay length. Adjust 'e' and 'l' parameters to change the reverb's 'texture' or 'geometry'. High room values can cause oscillation."
},
    nodeclass: "MozziReverb",
    description: "Configurable ReverbTank.",
    mozzi: {
        rate: "audio",
        includes: ["#include <ReverbTank.h>"],
        defaults: {"in":"0","mix":"128","room":"85","e1":"37","e2":"77","e3":"127","l1":"117","l2":"255"},
        global: function(n,v){ return "ReverbTank "+v+";"; },
        control: function(n,v,i){ 
            return v+".setFeebackLevel((int8_t)((int)"+i.room+" - 128));\n\t" +
                   v+".setEarlyReflections((int8_t)"+i.e1+", (int8_t)"+i.e2+", (int8_t)"+i.e3+");\n\t" +
                   v+".setLoopDelays((int8_t)"+i.l1+", (uint8_t)"+i.l2+");";
        },
        audio: function(n,v,i){ 
            return "int "+v+"_wet = "+v+".next((int)"+i.in+");\n\t" +
                   v+"_out = (int)((((long)"+i.in+" * (255 - (int)"+i.mix+")) + ((long)"+v+"_wet * (int)"+i.mix+")) >> 8);"; 
        },
    },
    rpdnode: {
    "title": "Reverb Tank",
    "inlets": {
        "in": { "type": "mozziflow/string", "no_text": true, "color": "bipolar_8" },
        "mix": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_8" },
        "room": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_8" },
        "e1": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_8" },
        "e2": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_8" },
        "e3": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_8" },
        "l1": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_8" },
        "l2": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_8" }
    },
    "outlets": {
        "out": { "type": "mozziflow/string", "color": "bipolar_8" }
    }
}
});


NodeLibrary.push({
    nodetype: 'filter/mozzi_multires',
    help: {
        "summary": "Advanced 4-output Resonant Filter. Computes LowPass, HighPass, BandPass, and Notch simultaneously with high efficiency.",
        "inlets": {
            "in": "Audio input signal.",
            "cutoff": "Cutoff frequency (0-255).",
            "res": "Resonance intensity (0-255)."
        },
        "outlets": {
            "low": "Low-Pass output.",
            "high": "High-Pass output.",
            "band": "Band-Pass output.",
            "notch": "Notch (Band-Reject) output."
        },
        "usage": "Extremely CPU efficient. Use it when you need multiple filtered versions of the same sound at once."
    },
    nodeclass: "MozziMultiRes",
    description: "4-output efficient filter.",
    mozzi: {
        rate: "audio",
        includes: ["#include <ResonantFilter.h>"],
        defaults: {"in":"0","cutoff":"128","res":"128"},
        global: function(n,v){ return "MultiResonantFilter<uint8_t> " + v + ";"; },
        control: function(n,v,i){ return v + ".setCutoffFreqAndResonance((uint8_t)" + i.cutoff + ", (uint8_t)" + i.res + ");"; },
        audio: function(n,v,i){ 
            return v + ".next((int)" + i.in + ");\n\t" +
                   v + "_low = " + v + ".low();\n\t" +
                   v + "_high = " + v + ".high();\n\t" +
                   v + "_band = " + v + ".band();\n\t" +
                   v + "_notch = " + v + ".notch();"; 
        }
    },
    rpdnode: {
        "title": "MultiRes Filter",
        "inlets": {
            "in": { "type": "mozziflow/string", "no_text": true, "color": "bipolar_8" },
            "cutoff": { "type": "mozziflow/string", "label": "Freq / Cutoff", "is_control": true, "color": "unipolar_8" },
            "res": { "type": "mozziflow/string", "label": "Resonance / Q", "is_control": true, "color": "unipolar_8" }
        },
        "outlets": {
            "low": { "type": "mozziflow/string", "color": "bipolar_8" },
            "high": { "type": "mozziflow/string", "color": "bipolar_8" },
            "band": { "type": "mozziflow/string", "color": "bipolar_8" },
            "notch": { "type": "mozziflow/string", "color": "bipolar_8" }
        }
    }
});