// Mozzi Node Definitions - LFO CATEGORY
// Generated by MozziFlow Intelligent Agent

NodeLibrary.push({
    nodetype: 'lfo/mozzi_lfo_sin',
    help: {
    "summary": "Sine wave LFO for smooth modulation.",
    "usage": "Use this to modulate filters or pitch. Output range: -128 to 127 (Bipolar)."
},
    nodeclass: "MozziLFOSin",
    description: "Sine LFO (Control).\n",
    mozzi: {
        rate: "control",
        includes: ["#include <Oscil.h>","#include <tables/sin2048_int8.h>"],
        defaults: {"freq":"1"},
        global: function(n, v) { return "Oscil<SIN2048_NUM_CELLS, CONTROL_RATE> "+v+"(SIN2048_DATA);"; },
        setup: function(n, v, i, r, s) { if (s.freq) return v+".setFreq("+i.freq+");"; return ""; },
        control: function(n, v, i, r, s) { 
            var code = "";
            if (!s.freq) code += v+".setFreq("+i.freq+"); ";
            return code + v+"_out = "+v+".next()"; 
        },
        audio: function(n, v, i) { return ""; },
    },
    rpdnode: {
    "title": "Sine LFO",
        inlets: {
            "freq": {
                "type": "mozziflow/float_32",
                "is_control": true
            }
        },    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "bipolar_8"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'lfo/mozzi_lfo_tri',
    help: {
    "summary": "Triangle wave LFO.",
    "usage": "Ideal for linear sweeps. Output range: -128 to 127 (Bipolar)."
},
    nodeclass: "MozziLFOTri",
    description: "Triangle LFO (Control).\n",
    mozzi: {
        rate: "control",
        includes: ["#include <Oscil.h>","#include <tables/triangle2048_int8.h>"],
        defaults: {"freq":"1"},
        global: function(n, v) { return "Oscil<TRIANGLE2048_NUM_CELLS, CONTROL_RATE> "+v+"(TRIANGLE2048_DATA);"; },
        setup: function(n, v, i, r, s) { if (s.freq) return v+".setFreq("+i.freq+");"; return ""; },
        control: function(n, v, i, r, s) { 
            var code = "";
            if (!s.freq) code += v+".setFreq("+i.freq+"); ";
            return code + v+"_out = "+v+".next()"; 
        },
        audio: function(n, v, i) { return ""; },
    },
    rpdnode: {
    "title": "Triangle LFO",
        inlets: {
            "freq": {
                "type": "mozziflow/float_32",
                "is_control": true
            }
        },    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "bipolar_8"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'lfo/mozzi_lfo_square',
    help: {
    "summary": "Square wave LFO.",
    "usage": "Use for rhythmic trills or on/off modulation. Output: -128 or 127."
},
    nodeclass: "MozziLFOSquare",
    description: "Square LFO (Control).\n",
    mozzi: {
        rate: "control",
        includes: ["#include <Oscil.h>","#include <tables/square_no_alias_2048_int8.h>"],
        defaults: {"freq":"1"},
        global: function(n, v) { return "Oscil<SQUARE_NO_ALIAS_2048_NUM_CELLS, CONTROL_RATE> "+v+"(SQUARE_NO_ALIAS_2048_DATA);"; },
        setup: function(n, v, i, r, s) { if (s.freq) return v+".setFreq("+i.freq+");"; return ""; },
        control: function(n, v, i, r, s) { 
            var code = "";
            if (!s.freq) code += v+".setFreq("+i.freq+"); ";
            return code + v+"_out = "+v+".next()"; 
        },
        audio: function(n, v, i) { return ""; },
        inlet_rates: {"freq":"control"},
    },
    rpdnode: {
    "title": "Square LFO",
        inlets: {
            "freq": {
                "type": "mozziflow/float_32",
                "is_control": true
            }
        },    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "bipolar_8"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'lfo/mozzi_lfo_saw',
    help: {
    "summary": "Sawtooth wave LFO.",
    "usage": "Excellent for rhythmic 'rising' effects. Output: -128 to 127."
},
    nodeclass: "MozziLFOSaw",
    description: "Sawtooth LFO (Control).\n",
    mozzi: {
        rate: "control",
        includes: ["#include <Oscil.h>","#include <tables/saw2048_int8.h>"],
        defaults: {"freq":"1"},
        global: function(n, v) { return "Oscil<SAW2048_NUM_CELLS, CONTROL_RATE> "+v+"(SAW2048_DATA);"; },
        setup: function(n, v, i, r, s) { if (s.freq) return v+".setFreq("+i.freq+");"; return ""; },
        control: function(n, v, i, r, s) { 
            var code = "";
            if (!s.freq) code += v+".setFreq("+i.freq+"); ";
            return code + v+"_out = "+v+".next()"; 
        },
        audio: function(n, v, i) { return ""; },
    },
    rpdnode: {
    "title": "Saw LFO",
        inlets: {
            "freq": {
                "type": "mozziflow/float_32",
                "is_control": true
            }
        },    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "bipolar_8"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'lfo/mozzi_lfo_sin_10',
    help: {
    "summary": "True High-Res Sine LFO (10-bit)."
},
    nodeclass: "MozziLFOSin10",
    description: "Sine LFO (10-bit).\n",
    mozzi: {
        rate: "control",
        includes: ["#include <Phasor.h>","#include <tables/cos4096_int16.h>","#include <mozzi_pgmspace.h>"],
        defaults: {"freq":"1"},
        global: function(n, v) { return 'Phasor<CONTROL_RATE> ' + v + '_ph;'; },
        setup: function(n, v, i, r, s) { if (s.freq) return v+"_ph.setFreq("+i.freq+");"; return ""; },
        control: function(n, v, i, r, s) { 
            var code = "";
            if (!s.freq) code += v+"_ph.setFreq("+i.freq+");\n\t";
            return code + v + '_out = (int)((FLASH_OR_READ_PGM<const int16_t>(COS4096X16_DATA + (' + v + '_ph.next() >> 20)) + 32768) >> 6);'; 
        },
        audio: function(n,v,i){ return ''; },
    },
    rpdnode: {
    "title": "Sine LFO 10b",
        inlets: {
            "freq": {
                "type": "mozziflow/float_32",
                "is_control": true
            }
        },    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "unipolar_16" // 10-bit is high res
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'lfo/mozzi_lfo_sin_12',
    help: {
    "summary": "True High-Res Sine LFO (12-bit)."
},
    nodeclass: "MozziLFOSin12",
    description: "Sine LFO (12-bit).\n",
    mozzi: {
        rate: "control",
        includes: ["#include <Phasor.h>","#include <tables/cos4096_int16.h>","#include <mozzi_pgmspace.h>"],
        defaults: {"freq":"1"},
        global: function(n, v) { return 'Phasor<CONTROL_RATE> ' + v + '_ph;'; },
        setup: function(n, v, i, r, s) { if (s.freq) return v+"_ph.setFreq("+i.freq+");"; return ""; },
        control: function(n, v, i, r, s) { 
            var code = "";
            if (!s.freq) code += v+"_ph.setFreq("+i.freq+");\n\t";
            return code + v + '_out = (int)((FLASH_OR_READ_PGM<const int16_t>(COS4096X16_DATA + (' + v + '_ph.next() >> 20)) + 32768) >> 4);'; 
        },
        audio: function(n,v,i){ return ''; },
        inlet_rates: {"freq":"control"},
    },
    rpdnode: {
    "title": "Sine LFO 12b",
        inlets: {
            "freq": {
                "type": "mozziflow/float_32",
                "is_control": true
            }
        },    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "unipolar_16" // 12-bit
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'lfo/mozzi_pulse',
    help: {
        "summary": "Pulse Wave LFO with PWM (Pulse Width Modulation).",
        "inlets": {
            "freq": "Frequency in Hz (e.g. 2 for 120bpm).",
            "width": "Pulse width (0-255). 127 is 50% square."
        },
        "outlets": {
            "out": "Pulse signal: 255 (High) or 0 (Low)."
        },
        "usage": "Use this as a GATE for ADSR envelopes. Adjust 'width' to control how long the note is held. 'freq' controls the tempo."
    },
    nodeclass: "MozziLFOPulse",
    description: "Pulse LFO (PWM).\n",
    mozzi: {
        rate: "control",
        includes: ["#include <Phasor.h>"],
        defaults: {"freq":"1", "width":"127"},
        global: function(n, v) { return "Phasor<CONTROL_RATE> "+v+";"; },
        setup: function(n, v, i, r, s) { if (s.freq) return v+".setFreq("+i.freq+");"; return ""; },
        control: function(n, v, i, r, s) { 
            var code = "";
            if (!s.freq) code += v+".setFreq("+i.freq+");\n\t";
            return code + v+"_out = ("+v+".next() >> 24) < (int)"+i.width+" ? 255 : 0;"; 
        },
        audio: function(n, v, i) { return ""; },
        inlet_rates: {"freq":"control", "width":"control"},
    },
    rpdnode: {
    "title": "Pulse LFO",
        inlets: {
            "freq": {
                "type": "mozziflow/float_32",
                "is_control": true
            },
            "width": {
                "type": "mozziflow/string",
                "default": "127",
                "is_control": true,
                "color": "unipolar_8"
            }
        },    
        "outlets": {
            "out": {
                "type": "mozziflow/string",
                "color": "logic"
            }
        }
    }
});
NodeLibrary.push({
    nodetype: 'lfo/mozzi_lfo_generic',
    help: {
        "summary": "Generic Low Frequency Oscillator (LFO) using custom wavetables.",
        "inlets": {
            "freq": "Oscillation frequency in Hz.",
            "table": "The wavetable to use (e.g., Sine, Triangle, Square)."
        },
        "outlets": {
            "out": "Bipolar LFO output (-128 to 127)."
        },
        "usage": "The ultimate modulation source. Unlike fixed LFOs, this lets you use ANY waveform as a modulator. Runs at CONTROL_RATE for efficiency."
    },
    nodeclass: "MozziLFOGeneric",
    description: "Custom Wavetable LFO.\n",
    mozzi: {
        rate: "control",
        includes: ["#include <Oscil.h>", "#include <tables/sin2048_int8.h>", "#include <tables/triangle2048_int8.h>", "#include <tables/saw2048_int8.h>", "#include <tables/square_no_alias_2048_int8.h>"],
        defaults: {"freq":"1"},
        global: function(n,v){
            var table = (n.data && n.data.tableName) ? n.data.tableName : "SIN2048_DATA";
            var size = (n.data && n.data.tableSize) ? n.data.tableSize : "2048";
            return "Oscil<" + size + ", CONTROL_RATE> " + v + "(" + table + ");"; 
        },
        setup: function(n, v, i, r, s) { if (s.freq) return v+".setFreq("+i.freq+");"; return ""; },
        control: function(n,v,i,r,s){ 
            var code = "";
            if (!s.freq) code += v+".setFreq("+i.freq+");\n\t";
            return code + v + "_out = " + v + ".next()"; 
        },
    },
    renderer: {
        'html': function(bodyElm, node) {
            if (!node.data) node.data = { tableName: "SIN2048_DATA", tableSize: "2048", label: "Sine" };
            var container = document.createElement('div');
            container.style.padding = "5px"; container.style.textAlign = "center";
            var label = document.createElement('div');
            label.innerText = "Waveform:"; label.style.fontSize = "9px";
            var select = document.createElement('select');
            select.className = "mozzi-buffer-select"; 
            var waves = [
                {n: "SIN2048_DATA", s: "2048", l: "Sine"},
                {n: "TRIANGLE2048_DATA", s: "2048", l: "Triangle"},
                {n: "SAW2048_DATA", s: "2048", l: "Saw"},
                {n: "SQUARE_NO_ALIAS_2048_DATA", s: "2048", l: "Square"}
            ];
            waves.forEach(function(w) {
                var opt = document.createElement('option');
                opt.value = w.n; opt.innerText = w.l;
                if (w.n === node.data.tableName) opt.selected = true;
                select.appendChild(opt);
            });
            select.onchange = function() {
                var val = this.value;
                var w = waves.find(function(x) { return x.n === val; });
                node.data.tableName = w.n; node.data.tableSize = w.s; node.data.label = w.l;
            };
            container.appendChild(label); container.appendChild(select);
            bodyElm.appendChild(container);
        }
    },
    rpdnode: {
        "title": "Generic LFO",
        "inlets": { "freq": { "type": "mozziflow/float_32", "is_control": true } },
        "outlets": { "out": { "type": "mozziflow/string", "color": "bipolar_8" } }
    }
});
