// Mozzi Node Definitions - LOGIC CATEGORY
// Generated by MozziFlow Intelligent Agent

NodeLibrary.push({
    nodetype: 'logic/and',
    help: { "summary": "Boolean AND. Outputs 255 if both A and B are greater than 0." },
    nodeclass: "LogicAND",
    description: "Gate AND",
    mozzi: {
        defaults: {"a":"0","b":"0"},
        audio: function(n,v,i) { return v+"_out = ((int)"+i.a+" > 0 && (int)"+i.b+" > 0) ? 255 : 0;"; },
    },
    rpdnode: {
        "title": "AND",
        inlets: { "a": { "type": "mozziflow/string", "color": "logic" }, "b": { "type": "mozziflow/string", "color": "logic" } },
        outlets: { "out": { "type": "mozziflow/string", "color": "logic" } }
    }
});

NodeLibrary.push({
    nodetype: 'logic/or',
    help: { "summary": "Boolean OR. Outputs 255 if either A or B is greater than 0." },
    nodeclass: "LogicOR",
    description: "Gate OR",
    mozzi: {
        defaults: {"a":"0","b":"0"},
        audio: function(n,v,i) { return v+"_out = ((int)"+i.a+" > 0 || (int)"+i.b+" > 0) ? 255 : 0;"; },
    },
    rpdnode: {
        "title": "OR",
        inlets: { "a": { "type": "mozziflow/string", "color": "logic" }, "b": { "type": "mozziflow/string", "color": "logic" } },
        outlets: { "out": { "type": "mozziflow/string", "color": "logic" } }
    }
});

NodeLibrary.push({
    nodetype: 'logic/not',
    help: { "summary": "Boolean NOT. Inverts the signal: Outputs 255 if input is 0, and 0 if input is greater than 0." },
    nodeclass: "LogicNOT",
    description: "Inverter",
    mozzi: {
        defaults: {"in":"0"},
        audio: function(n,v,i) { return v+"_out = ((int)"+i.in+" == 0) ? 255 : 0;"; },
    },
    rpdnode: {
        "title": "NOT",
        inlets: { "in": { "type": "mozziflow/string", "color": "logic" } },
        outlets: { "out": { "type": "mozziflow/string", "color": "logic" } }
    }
});

NodeLibrary.push({
    nodetype: 'logic/xor',
    help: { "summary": "Boolean XOR. Outputs 255 if A and B are different (one is 0 and the other is > 0)." },
    nodeclass: "LogicXOR",
    description: "Gate XOR",
    mozzi: {
        defaults: {"a":"0","b":"0"},
        audio: function(n,v,i) { return v+"_out = (((int)"+i.a+" > 0) != ((int)"+i.b+" > 0)) ? 255 : 0;"; },
    },
    rpdnode: {
        "title": "XOR",
        inlets: { "a": { "type": "mozziflow/string", "color": "logic" }, "b": { "type": "mozziflow/string", "color": "logic" } },
        outlets: { "out": { "type": "mozziflow/string", "color": "logic" } }
    }
});
