// Mozzi Node Definitions - MATH CATEGORY
// Generated by MozziFlow Intelligent Agent

NodeLibrary.push({
    nodetype: 'math/add',
    nodeclass: "MathAdd",
    description: "Adds signals.",
    mozzi: {
        defaults: {"a":"0","b":"0"},
        audio: function(n,v,i) { return v + "_out = " + i.a + " + " + i.b + ";"; },
    },
    rpdnode: {
    "title": "Add",
    "inlets": { "a": { "type": "mozziflow/string" }, "b": { "type": "mozziflow/string" } },
    "outlets": { "out": { "type": "mozziflow/string" } }
}
});

NodeLibrary.push({
    nodetype: 'math/sub',
    nodeclass: "MathSub",
    description: "Subtracts signals.",
    mozzi: {
        defaults: {"a":"0","b":"0"},
        audio: function(n,v,i) { return v + "_out = " + i.a + " - " + i.b + ";"; },
    },
    rpdnode: {
    "title": "Subtract",
    "inlets": { "a": { "type": "mozziflow/string" }, "b": { "type": "mozziflow/string" } },
    "outlets": { "out": { "type": "mozziflow/string" } }
}
});

NodeLibrary.push({
    nodetype: 'math/mul',
    nodeclass: "MathMul",
    description: "Multiplies signals.",
    mozzi: {
        defaults: {"a":"0","b":"1"},
        audio: function(n,v,i) { return v + "_out = (int)((long)" + i.a + " * " + i.b + ");"; },
    },
    rpdnode: {
    "title": "Multiply",
    "inlets": { "a": { "type": "mozziflow/string" }, "b": { "type": "mozziflow/string" } },
    "outlets": { "out": { "type": "mozziflow/string" } }
}
});

NodeLibrary.push({
    nodetype: 'math/div',
    nodeclass: "MathDiv",
    description: "Divides signals.",
    mozzi: {
        defaults: {"a":"0","b":"1"},
        audio: function(n,v,i) { return v + "_out = " + i.b + " != 0 ? (int)(((long)" + i.a + " << 8) / " + i.b + ") : 0;"; },
    },
    rpdnode: {
    "title": "Divide",
    "inlets": { "a": { "type": "mozziflow/string" }, "b": { "type": "mozziflow/string" } },
    "outlets": { "out": { "type": "mozziflow/string" } }
}
});

NodeLibrary.push({
    nodetype: 'math/abs',
    nodeclass: "MathAbs",
    description: "Absolute value.",
    mozzi: {
        defaults: {"in":"0"},
        audio: function(n,v,i) { return v + "_out = abs((int)" + i.in + ");"; },
    },
    rpdnode: {
    "title": "Absolute",
    "inlets": { "in": { "type": "mozziflow/string", "no_text": true } },
    "outlets": { "out": { "type": "mozziflow/string", "color": "unipolar_8" } }
}
});

NodeLibrary.push({
    nodetype: 'math/min',
    nodeclass: "MathMin",
    description: "Smaller of two.",
    mozzi: {
        defaults: {"a":"0","b":"0"},
        audio: function(n,v,i) { return v + "_out = min((int)" + i.a + ", (int)" + i.b + ");"; },
    },
    rpdnode: {
    "title": "Minimum",
    "inlets": { "a": { "type": "mozziflow/string" }, "b": { "type": "mozziflow/string" } },
    "outlets": { "out": { "type": "mozziflow/string" } }
}
});

NodeLibrary.push({
    nodetype: 'math/max',
    nodeclass: "MathMax",
    description: "Larger of two.",
    mozzi: {
        defaults: {"a":"0","b":"0"},
        audio: function(n,v,i) { return v + "_out = max((int)" + i.a + ", (int)" + i.b + ");"; },
    },
    rpdnode: {
    "title": "Maximum",
    "inlets": { "a": { "type": "mozziflow/string" }, "b": { "type": "mozziflow/string" } },
    "outlets": { "out": { "type": "mozziflow/string" } }
}
});

NodeLibrary.push({
    nodetype: 'math/mozzi_intmap',
    nodeclass: "MozziIntMap",
    description: "Fast integer mapping.",
    mozzi: {
        rate: "control",
        includes: ["#include <IntMap.h>"],
        defaults: {"in":"0", "imin":"0", "imax":"1023", "omin":"0", "omax":"255"},
        global: function(n,v){ 
            var getVal = function(a, d) { if (n.nodeinletvalue && n.nodeinletvalue[a]) return n.nodeinletvalue[a][1]; return d; };
            return "IntMap " + v + "(" + getVal('imin','0') + "," + getVal('imax','1023') + "," + getVal('omin','0') + "," + getVal('omax','255') + ");"; 
        },
        audio: function(n,v,i){ return v+"_out = "+v+"((int)"+i.in+");"; },
    },
    rpdnode: {
    "title": "IntMap",
    "inlets": {
        "in": { "type": "mozziflow/string", "no_text": true, "color": "unipolar_16" },
        "imin": { "type": "mozziflow/string", "default": "0", "color": "unipolar_16" },
        "imax": { "type": "mozziflow/string", "default": "1023", "color": "unipolar_16" },
        "omin": { "type": "mozziflow/string", "default": "0", "color": "unipolar_16" },
        "omax": { "type": "mozziflow/string", "default": "255", "color": "unipolar_16" }
    },
    "outlets": { "out": { "type": "mozziflow/string", "color": "unipolar_8" } }
}
});

NodeLibrary.push({
    nodetype: 'math/mozzi_map',
    nodeclass: "MozziMap",
    description: "Manual range mapper.",
    mozzi: {
        audio: function(n,v,i){ 
            return v+"_out = map((int)"+i.in+", (int)"+i.imin+", (int)"+i.imax+", (int)"+i.omin+", (int)"+i.omax+");"; 
        },
    },
    rpdnode: {
    "title": "Map Range",
    "inlets": {
        "in": { "type": "mozziflow/string", "no_text": true, "color": "unipolar_16" },
        "imin": { "type": "mozziflow/string", "default": "-128" },
        "imax": { "type": "mozziflow/string", "default": "127" },
        "omin": { "type": "mozziflow/string", "default": "20" },
        "omax": { "type": "mozziflow/string", "default": "3000" }
    },
    "outlets": { "out": { "type": "mozziflow/string", "color": "unipolar_16" } }
}
});

NodeLibrary.push({
    nodetype: 'math/mtof',
    nodeclass: "MathMTOF",
    description: "MIDI to Freq",
    mozzi: {
        includes: ["#include <mozzi_midi.h>"],
        defaults: {"note":"60"},
        audio: function(n,v,i) { return v+"_out = (float)mtof((float)"+i.note+");"; },
    },
    rpdnode: {
        "title": "Midi->Freq",
        inlets: { "note": { "type": "mozziflow/string", "color": "unipolar_8" } },
        outlets: { "out": { "type": "mozziflow/float_32" } }
    }
});

NodeLibrary.push({
    nodetype: 'math/to_int',
    nodeclass: "MathToInt",
    description: "Cast to Integer",
    mozzi: {
        defaults: {"in":"0"},
        audio: function(n,v,i) { return v+"_out = (int)"+i.in+";"; },
    },
    rpdnode: {
        "title": "To Int",
        inlets: { "in": { "type": "mozziflow/string" } },
        outlets: { "out": { "type": "mozziflow/string" } }
    }
});

NodeLibrary.push({
    nodetype: 'math/to_float',
    nodeclass: "MathToFloat",
    description: "Cast to Float",
    mozzi: {
        defaults: {"in":"0"},
        audio: function(n,v,i) { return v+"_out = (float)"+i.in+";"; },
    },
    rpdnode: {
        "title": "To Float",
        inlets: { "in": { "type": "mozziflow/string" } },
        outlets: { "out": { "type": "mozziflow/float_32" } }
    }
});

NodeLibrary.push({
    nodetype: 'math/compare_gt',
    nodeclass: "MathGT",
    description: "Compare: A > B",
    mozzi: {
        defaults: {"a":"0","b":"0"},
        audio: function(n,v,i) { return v+"_out = ((int)"+i.a+" > (int)"+i.b+") ? 255 : 0;"; },
    },
    rpdnode: {
    "title": "A > B",
        inlets: { "a": { "type": "mozziflow/string" }, "b": { "type": "mozziflow/string" } },
        outlets: { "out": { "type": "mozziflow/string", "color": "logic" } }
    }
});

NodeLibrary.push({
    nodetype: 'math/shl',
    nodeclass: "MathSHL",
    description: "Shift Left",
    mozzi: {
        defaults: {"a":"0","b":"1"},
        audio: function(n,v,i) { return v+"_out = (int)"+i.a+" << (int)"+i.b+";"; },
    },
    rpdnode: {
        "title": "Shift Left",
        inlets: { "a": { "type": "mozziflow/string", "color": "unipolar_16" }, "b": { "type": "mozziflow/string", "color": "unipolar_8" } },
        outlets: { "out": { "type": "mozziflow/string", "color": "unipolar_16" } }
    }
});

NodeLibrary.push({
    nodetype: 'math/shr',
    nodeclass: "MathSHR",
    description: "Shift Right",
    mozzi: {
        defaults: {"a":"0","b":"1"},
        audio: function(n,v,i) { return v+"_out = (int)"+i.a+" >> (int)"+i.b+";"; },
    },
    rpdnode: {
        "title": "Shift Right",
        inlets: { "a": { "type": "mozziflow/string", "color": "unipolar_16" }, "b": { "type": "mozziflow/string", "color": "unipolar_8" } },
        outlets: { "out": { "type": "mozziflow/string", "color": "unipolar_16" } }
    }
});

NodeLibrary.push({
    nodetype: 'math/add_f',
    nodeclass: "MathAddF",
    description: "Float Add",
    mozzi: {
        defaults: {"a":"0.0","b":"0.0"},
        audio: function(n,v,i) { return v+"_out = (float)"+i.a+" + (float)"+i.b+";"; },
    },
    rpdnode: {
        "title": "Add (F)",
        inlets: { "a": { "type": "mozziflow/float_32" }, "b": { "type": "mozziflow/float_32" } },
        outlets: { "out": { "type": "mozziflow/float_32" } }
    }
});

NodeLibrary.push({
    nodetype: 'math/sub_f',
    nodeclass: "MathSubF",
    description: "Float Subtract",
    mozzi: {
        defaults: {"a":"0.0","b":"0.0"},
        audio: function(n,v,i) { return v+"_out = (float)"+i.a+" - (float)"+i.b+";"; },
    },
    rpdnode: {
        "title": "Sub (F)",
        inlets: { "a": { "type": "mozziflow/float_32" }, "b": { "type": "mozziflow/float_32" } },
        outlets: { "out": { "type": "mozziflow/float_32" } }
    }
});

NodeLibrary.push({
    nodetype: 'math/mul_f',
    nodeclass: "MathMulF",
    description: "Float Multiply",
    mozzi: {
        defaults: {"a":"1.0","b":"1.0"},
        audio: function(n,v,i) { return v+"_out = (float)"+i.a+" * (float)"+i.b+";"; },
    },
    rpdnode: {
        "title": "Mul (F)",
        inlets: { "a": { "type": "mozziflow/float_32" }, "b": { "type": "mozziflow/float_32" } },
        outlets: { "out": { "type": "mozziflow/float_32" } }
    }
});

NodeLibrary.push({
    nodetype: 'math/div_f',
    nodeclass: "MathDivF",
    description: "Float Divide",
    mozzi: {
        defaults: {"a":"1.0","b":"1.0"},
        audio: function(n,v,i) { return v+"_out = ((float)"+i.b+" != 0.0f) ? ((float)"+i.a+" / (float)"+i.b+") : 0.0f;"; },
    },
    rpdnode: {
        "title": "Div (F)",
        inlets: { "a": { "type": "mozziflow/float_32" }, "b": { "type": "mozziflow/float_32" } },
        outlets: { "out": { "type": "mozziflow/float_32" } }
    }
});
