// Mozzi Node Definitions - OUTPUT CATEGORY
// Generated by MozziFlow Intelligent Agent

NodeLibrary.push({
    nodetype: 'output/digital',
    help: {
    "summary": "Physical output writer for Arduino Digital Pins.",
    "inlets": {
        "pin": "Digital pin number.",
        "val": "Boolean state (0 = LOW, 255 = HIGH)."
    },
    "outlets": {},
    "usage": "The bridge between your software patch and the physical world. Use it to turn on LEDs, trigger relays, or send sync pulses to external gear."
},
    nodeclass: "DigOut",
    description: "Arduino Digital Output.",
    mozzi: {
        defaults: {"pin":"13","val":"0"},
        setup: function(n,v,i){ return "pinMode("+i.pin+", OUTPUT);"; },
        control: function(n,v,i){ return "digitalWrite("+i.pin+", (int)"+i.val+" > 0 ? HIGH : LOW);"; },
        inlet_rates: {"pin":"control","val":"control"},
    },
    rpdnode: {
    "title": "Digital Out",
    "inlets": {
        "pin": {
            "type": "mozziflow/string",
            "is_control": true
        },
        "val": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "logic"
        }
    },
    "outlets": {}
}
});

NodeLibrary.push({
    nodetype: 'output/analog',
    help: {
    "summary": "Physical PWM (Pulse Width Modulation) writer for Arduino pins.",
    "inlets": {
        "pin": "PWM-capable pin (e.g., 3, 5, 6, 10, 11).",
        "val": "Duty cycle intensity (0-255)."
    },
    "outlets": {},
    "usage": "Control the brightness of an LED or the speed of a small DC motor. Note: Pin 9 is usually reserved for Mozzi audio output."
},
    nodeclass: "AnaOut",
    description: "Arduino PWM Output.",
    mozzi: {
        defaults: {"pin":"9","val":"0"},
        setup: function(n,v,i){ return "pinMode("+i.pin+", OUTPUT);"; },
        control: function(n,v,i){ return "analogWrite("+i.pin+", (int)"+i.val+");"; },
        inlet_rates: {"pin":"control","val":"control"},
    },
    rpdnode: {
    "title": "PWM Out",
    "inlets": {
        "pin": {
            "type": "mozziflow/string",
            "is_control": true
        },
        "val": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "unipolar_8"
        }
    },
    "outlets": {}
}
});

NodeLibrary.push({
    nodetype: 'output/arduino_shift595_1',
    help: {
    "summary": "Driver for the 74HC595 8-bit Serial-to-Parallel Shift Register.",
    "inlets": {
        "data_pin": "Serial Data Input (DS).",
        "latch": "Storage Register Clock (ST_CP/Latch).",
        "clock": "Shift Register Clock (SH_CP).",
        "bits0": "8-bit data byte (0-255)."
    },
    "outlets": {},
    "usage": "A 'port expander' that gives you 8 digital outputs using only 3 pins. Perfect for driving LED arrays or 7-segment displays. Connect Data, Latch, and Clock to the corresponding pins on your chip."
},
    nodeclass: "ArduinoShift595_1",
    description: "74HC595 (1 Chip).",
    mozzi: {
        rate: "control",
        defaults: {"data_pin":"11","latch":"12","clock":"13","bits0":"0"},
        setup: function(n,v,i){ return "pinMode("+i.data_pin+", OUTPUT); pinMode("+i.latch+", OUTPUT); pinMode("+i.clock+", OUTPUT);"; },
        control: function(n,v,i){ return "digitalWrite("+i.latch+", LOW); shiftOut("+i.data_pin+", "+i.clock+", MSBFIRST, (uint8_t)"+i.bits0+"); digitalWrite("+i.latch+", HIGH);"; },
    },
    rpdnode: {
    "title": "Shift 595 (1)",
    "inlets": {
        "data_pin": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "logic"
        },
        "latch": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "logic"
        },
        "clock": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "logic"
        },
        "bits0": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "unipolar_8"
        }
    },
    "outlets": {}
}
});

NodeLibrary.push({
    nodetype: 'output/arduino_shift595_2',
    help: {
    "summary": "Driver for two cascaded (chained) 74HC595 chips.",
    "inlets": {
        "data_pin": "Serial Data Input (DS).",
        "latch": "Storage Register Clock (Latch).",
        "clock": "Shift Register Clock.",
        "bits0": "Data byte for Chip 1.",
        "bits1": "Data byte for Chip 2."
    },
    "outlets": {},
    "usage": "Control 16 digital outputs using only 3 Arduino pins. Wiring: Connect Q7' (serial out) of chip 1 to DS of chip 2. Both chips share Latch and Clock pins."
},
    nodeclass: "ArduinoShift595_2",
    description: "74HC595 (2 Chips).",
    mozzi: {
        rate: "control",
        defaults: {"data_pin":"11","latch":"12","clock":"13","bits0":"0","bits1":"0"},
        setup: function(n,v,i){ return "pinMode("+i.data_pin+", OUTPUT); pinMode("+i.latch+", OUTPUT); pinMode("+i.clock+", OUTPUT);"; },
        control: function(n,v,i){ return "digitalWrite("+i.latch+", LOW); shiftOut("+i.data_pin+", "+i.clock+", MSBFIRST, (uint8_t)"+i.bits1+"); shiftOut("+i.data_pin+", "+i.clock+", MSBFIRST, (uint8_t)"+i.bits0+"); digitalWrite("+i.latch+", HIGH);"; },
        inlet_rates: {"bits0":"control","bits1":"control"},
    },
    rpdnode: {
    "title": "Shift 595 (2)",
    "inlets": {
        "data_pin": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "logic"
        },
        "latch": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "logic"
        },
        "clock": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "logic"
        },
        "bits0": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "unipolar_8"
        },
        "bits1": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "unipolar_8"
        }
    },
    "outlets": {}
}
});

NodeLibrary.push({
    nodetype: 'output/arduino_shift595_3',
    help: {
    "summary": "Driver for three cascaded (chained) 74HC595 chips.",
    "inlets": {
        "data_pin": "Serial Data Input (DS).",
        "latch": "Storage Register Clock (Latch).",
        "clock": "Shift Register Clock.",
        "bits0": "Data byte for Chip 1.",
        "bits1": "Data byte for Chip 2.",
        "bits2": "Data byte for Chip 3."
    },
    "outlets": {},
    "usage": "Control 24 digital outputs. Chain the chips by connecting Q7' to DS of the next chip. Share the Latch and Clock signals across the entire chain."
},
    nodeclass: "ArduinoShift595_3",
    description: "74HC595 (3 Chips).",
    mozzi: {
        rate: "control",
        defaults: {"data_pin":"11","latch":"12","clock":"13","bits0":"0","bits1":"0","bits2":"0"},
        setup: function(n,v,i){ return "pinMode("+i.data_pin+", OUTPUT); pinMode("+i.latch+", OUTPUT); pinMode("+i.clock+", OUTPUT);"; },
        control: function(n,v,i){ return "digitalWrite("+i.latch+", LOW); shiftOut("+i.data_pin+", "+i.clock+", MSBFIRST, (uint8_t)"+i.bits2+"); shiftOut("+i.data_pin+", "+i.clock+", MSBFIRST, (uint8_t)"+i.bits1+"); shiftOut("+i.data_pin+", "+i.clock+", MSBFIRST, (uint8_t)"+i.bits0+"); digitalWrite("+i.latch+", HIGH);"; },
        inlet_rates: {"bits0":"control","bits1":"control","bits2":"control"},
    },
    rpdnode: {
    "title": "Shift 595 (3)",
    "inlets": {
        "data_pin": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "logic"
        },
        "latch": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "logic"
        },
        "clock": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "logic"
        },
        "bits0": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "unipolar_8"
        },
        "bits1": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "unipolar_8"
        },
        "bits2": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "unipolar_8"
        }
    },
    "outlets": {}
}
});

NodeLibrary.push({
    nodetype: 'output/arduino_shift595_4',
    help: {
    "summary": "Advanced driver for four cascaded (chained) 74HC595 chips.",
    "inlets": {
        "data_pin": "Serial Data Input (DS).",
        "latch": "Storage Register Clock (Latch).",
        "clock": "Shift Register Clock.",
        "bits0": "Data for Chip 1.",
        "bits1": "Data for Chip 2.",
        "bits2": "Data for Chip 3.",
        "bits3": "Data for Chip 4."
    },
    "outlets": {},
    "usage": "Provides 32 digital outputs. Used for building massive LED matrices or comprehensive control dashboards. Ensure your power supply can handle the current required for 32 active outputs."
},
    nodeclass: "ArduinoShift595_4",
    description: "74HC595 (4 Chips).",
    mozzi: {
        rate: "control",
        defaults: {"data_pin":"11","latch":"12","clock":"13","bits0":"0","bits1":"0","bits2":"0","bits3":"0"},
        setup: function(n,v,i){ return "pinMode("+i.data_pin+", OUTPUT); pinMode("+i.latch+", OUTPUT); pinMode("+i.clock+", OUTPUT);"; },
        control: function(n,v,i){ return "digitalWrite("+i.latch+", LOW); shiftOut("+i.data_pin+", "+i.clock+", MSBFIRST, (uint8_t)"+i.bits3+"); shiftOut("+i.data_pin+", "+i.clock+", MSBFIRST, (uint8_t)"+i.bits2+"); shiftOut("+i.data_pin+", "+i.clock+", MSBFIRST, (uint8_t)"+i.bits1+"); shiftOut("+i.data_pin+", "+i.clock+", MSBFIRST, (uint8_t)"+i.bits0+"); digitalWrite("+i.latch+", HIGH);"; },
        inlet_rates: {"bits0":"control","bits1":"control","bits2":"control","bits3":"control"},
    },
    rpdnode: {
    "title": "Shift 595 (4)",
    "inlets": {
        "data_pin": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "logic"
        },
        "latch": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "logic"
        },
        "clock": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "logic"
        },
        "bits0": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "unipolar_8"
        },
        "bits1": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "unipolar_8"
        },
        "bits2": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "unipolar_8"
        },
        "bits3": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "unipolar_8"
        }
    },
    "outlets": {}
}
});

NodeLibrary.push({
    nodetype: 'output/mozzi_out',
    help: {
    "summary": "The Master Audio Output node. Final gateway to sound.",
    "inlets": {
        "audio_in": "The final digital audio stream."
    },
    "outlets": {},
    "usage": "Every patch MUST have exactly one 'Output' node. It translates your digital signal (-128 to 127) into physical high-speed PWM on Pin 9. Connect your speaker or amplifier here."
},
    nodeclass: "MozziOut",
    description: "Audio Output.",
    mozzi: {
        rate: "audio",
        defaults: {"audio_in":"0"},
        audio: function(n,v,i){ return "return MonoOutput::from8Bit((int)"+i.audio_in+");"; },
    },
    rpdnode: {
    "title": "Output",
    "inlets": {
        "audio_in": {
            "type": "mozziflow/string",
            "no_text": true,
            "color": "bipolar_8"
        }
    },
    "outlets": {}
}
});


