// Mozzi Node Definitions - OUTPUT CATEGORY
// Generated by MozziFlow Intelligent Agent

NodeLibrary.push({
    nodetype: 'output/digital',
    nodeclass: "DigOut",
    description: "Arduino Digital Output.",
    mozzi: {
        rate: "control",
        defaults: {"pin":"13","val":"0"},
        setup: function(n,v,i){ return "pinMode("+i.pin+", OUTPUT);"; },
        control: function(n,v,i){ return "digitalWrite("+i.pin+", (int)"+i.val+" > 0 ? HIGH : LOW);"; },
    },
    rpdnode: {
    "title": "Digital Out",
    "inlets": {
        "pin": { "type": "mozziflow/string", "is_control": true },
        "val": { "type": "mozziflow/string", "is_control": true, "color": "logic" }
    },
    "outlets": {}
}
});

NodeLibrary.push({
    nodetype: 'output/analog',
    nodeclass: "AnaOut",
    description: "Arduino PWM Output.",
    mozzi: {
        rate: "control",
        defaults: {"pin":"9","val":"0"},
        setup: function(n,v,i){ return "pinMode("+i.pin+", OUTPUT);"; },
        control: function(n,v,i){ return "analogWrite("+i.pin+", (int)"+i.val+");"; },
    },
    rpdnode: {
    "title": "PWM Out",
    "inlets": {
        "pin": { "type": "mozziflow/string", "is_control": true },
        "val": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_8" }
    },
    "outlets": {}
}
});

NodeLibrary.push({
    nodetype: 'output/arduino_shift595_1',
    nodeclass: "ArduinoShift595_1",
    description: "74HC595 (1 Chip).",
    mozzi: {
        rate: "control",
        defaults: {"data_pin":"11","latch":"12","clock":"13","bits0":"0"},
        setup: function(n,v,i){ return "pinMode("+i.data_pin+", OUTPUT); pinMode("+i.latch+", OUTPUT); pinMode("+i.clock+", OUTPUT);"; },
        control: function(n,v,i){ return "digitalWrite("+i.latch+", LOW); shiftOut("+i.data_pin+", "+i.clock+", MSBFIRST, (uint8_t)"+i.bits0+"); digitalWrite("+i.latch+", HIGH);"; },
    },
    rpdnode: {
    "title": "Shift 595 (1)",
    "inlets": {
        "data_pin": { "type": "mozziflow/string", "is_control": true },
        "latch": { "type": "mozziflow/string", "is_control": true },
        "clock": { "type": "mozziflow/string", "is_control": true },
        "bits0": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_8" }
    },
    "outlets": {}
}
});

NodeLibrary.push({
    nodetype: 'output/arduino_shift595_2',
    nodeclass: "ArduinoShift595_2",
    description: "74HC595 (2 Chips).",
    mozzi: {
        rate: "control",
        defaults: {"data_pin":"11","latch":"12","clock":"13","bits0":"0","bits1":"0"},
        setup: function(n,v,i){ return "pinMode("+i.data_pin+", OUTPUT); pinMode("+i.latch+", OUTPUT); pinMode("+i.clock+", OUTPUT);"; },
        control: function(n,v,i){ return "digitalWrite("+i.latch+", LOW); shiftOut("+i.data_pin+", "+i.clock+", MSBFIRST, (uint8_t)"+i.bits1+"); shiftOut("+i.data_pin+", "+i.clock+", MSBFIRST, (uint8_t)"+i.bits0+"); digitalWrite("+i.latch+", HIGH);"; },
    },
    rpdnode: {
    "title": "Shift 595 (2)",
    "inlets": {
        "data_pin": { "type": "mozziflow/string", "is_control": true },
        "latch": { "type": "mozziflow/string", "is_control": true },
        "clock": { "type": "mozziflow/string", "is_control": true },
        "bits0": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_8" },
        "bits1": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_8" }
    },
    "outlets": {}
}
});

NodeLibrary.push({
    nodetype: 'output/arduino_shift595_3',
    nodeclass: "ArduinoShift595_3",
    description: "74HC595 (3 Chips).",
    mozzi: {
        rate: "control",
        defaults: {"data_pin":"11","latch":"12","clock":"13","bits0":"0","bits1":"0","bits2":"0"},
        setup: function(n,v,i){ return "pinMode("+i.data_pin+", OUTPUT); pinMode("+i.latch+", OUTPUT); pinMode("+i.clock+", OUTPUT);"; },
        control: function(n,v,i){ return "digitalWrite("+i.latch+", LOW); shiftOut("+i.data_pin+", "+i.clock+", MSBFIRST, (uint8_t)"+i.bits2+"); shiftOut("+i.data_pin+", "+i.clock+", MSBFIRST, (uint8_t)"+i.bits1+"); shiftOut("+i.data_pin+", "+i.clock+", MSBFIRST, (uint8_t)"+i.bits0+"); digitalWrite("+i.latch+", HIGH);"; },
    },
    rpdnode: {
    "title": "Shift 595 (3)",
    "inlets": {
        "data_pin": { "type": "mozziflow/string", "is_control": true },
        "latch": { "type": "mozziflow/string", "is_control": true },
        "clock": { "type": "mozziflow/string", "is_control": true },
        "bits0": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_8" },
        "bits1": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_8" },
        "bits2": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_8" }
    },
    "outlets": {}
}
});

NodeLibrary.push({
    nodetype: 'output/arduino_shift595_4',
    nodeclass: "ArduinoShift595_4",
    description: "74HC595 (4 Chips).",
    mozzi: {
        rate: "control",
        defaults: {"data_pin":"11","latch":"12","clock":"13","bits0":"0","bits1":"0","bits2":"0","bits3":"0"},
        setup: function(n,v,i){ return "pinMode("+i.data_pin+", OUTPUT); pinMode("+i.latch+", OUTPUT); pinMode("+i.clock+", OUTPUT);"; },
        control: function(n,v,i){ return "digitalWrite("+i.latch+", LOW); shiftOut("+i.data_pin+", "+i.clock+", MSBFIRST, (uint8_t)"+i.bits3+"); shiftOut("+i.data_pin+", "+i.clock+", MSBFIRST, (uint8_t)"+i.bits2+"); shiftOut("+i.data_pin+", "+i.clock+", MSBFIRST, (uint8_t)"+i.bits1+"); shiftOut("+i.data_pin+", "+i.clock+", MSBFIRST, (uint8_t)"+i.bits0+"); digitalWrite("+i.latch+", HIGH);"; },
    },
    rpdnode: {
    "title": "Shift 595 (4)",
    "inlets": {
        "data_pin": { "type": "mozziflow/string", "is_control": true },
        "latch": { "type": "mozziflow/string", "is_control": true },
        "clock": { "type": "mozziflow/string", "is_control": true },
        "bits0": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_8" },
        "bits1": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_8" },
        "bits2": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_8" },
        "bits3": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_8" }
    },
    "outlets": {}
}
});

NodeLibrary.push({
    nodetype: 'output/mozzi_out',
    nodeclass: "MozziOut",
    description: "Audio Output.",
    mozzi: {
        rate: "audio",
        defaults: {"audio_in":"0"},
        audio: function(n,v,i){ return "return MonoOutput::from8Bit((int)"+i.audio_in+");"; },
    },
    rpdnode: {
    "title": "Output",
    "inlets": {
        "audio_in": { "type": "mozziflow/string", "no_text": true, "color": "bipolar_8" }
    },
    "outlets": {}
}
});