// Mozzi Node Definitions - SIGNAL CATEGORY
// Generated by MozziFlow Intelligent Agent

NodeLibrary.push({
    nodetype: 'signal/mozzi_autorange',
    help: {
    "summary": "Dynamic signal normalization utility. Tracks min/max values.",
    "inlets": {
        "in": "Unstable or unpredictable input signal.",
        "imin": "Initial minimum expectation.",
        "imax": "Initial maximum expectation."
    },
    "outlets": {
        "min": "The lowest value recorded since start.",
        "max": "The highest value recorded since start."
    },
    "usage": "Perfect for calibrating sensors. Set imax to 4095 for CH32X035. The outputs will track the real range seen by the sensor."
},
    nodeclass: "MozziAutoRange",
    description: "Normalization.",
    mozzi: {
        rate: "control",
        includes: ["#include <AutoRange.h>"],
        defaults: {"in":"0", "imin":"0", "imax":"1023"},
        global: function(n,v){ 
            var getVal = function(a, d) {
                if (n.nodeinletvalue && n.nodeinletvalue[a]) return n.nodeinletvalue[a][1];
                return d;
            };
            return "AutoRange<int> "+v+"("+getVal('imin','0')+","+getVal('imax','1023')+");"; 
        },
        control: function(n,v,i){ return v+".next((int)"+i.in+");"; },
        audio: function(n,v){ return v+"_min="+v+".getMin(); "+v+"_max="+v+".getMax();"; },
    },
    rpdnode: {
    "title": "AutoRange",
    "inlets": {
        "in": {
            "type": "mozziflow/string",
            "no_text": true,
            "color": "unipolar_16"
        },
        "imin": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "imax": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" }
    },
    "outlets": {
        "min": {
            "type": "mozziflow/string",
            "color": "unipolar_16"
        },
        "max": {
            "type": "mozziflow/string",
            "color": "unipolar_16"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'signal/mozzi_eventdelay',
    help: {
    "summary": "Non-blocking trigger delay line.",
    "inlets": {
        "start": "Input trigger pulse.",
        "time": "Delay duration in milliseconds (ms)."
    },
    "outlets": {
        "out": "Delayed trigger pulse (255)."
    },
    "usage": "Essential for rhythmic composition. Use it to stagger drum hits or create 'ghost notes' by delaying a copy of a sequencer trigger."
},
    nodeclass: "MozziEventDelay",
    description: "One-shot pulse delay.",
    mozzi: {
        rate: "control",
        includes: ["#include <EventDelay.h>"],
        defaults: {"start":"0","time":"1000"},
        global: function(n,v){ return "EventDelay "+v+"; bool "+v+"_l=0;"; },
        control: function(n,v,i){ return "if((int)"+i.start+">0 && !"+v+"_l){ "+v+".start((uint32_t)"+i.time+"); "+v+"_l=1; } else if((int)"+i.start+"==0) "+v+"_l=0;\n\t"+v+"_out = "+v+".ready()?255:0;"; },
        audio: function(n,v,i){ return ""; },
        inlet_rates: {"start":"control","time":"control"},
    },
    rpdnode: {
    "title": "Event Delay",
    "inlets": {
        "start": {
            "type": "mozziflow/string",
            "no_text": true,
            "is_control": true,
            "color": "logic"
        },
        "time": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "unipolar_16"
        }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "logic"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'signal/mozzi_rollingaverage',
    help: {
    "summary": "Moving average filter for control signal stability.",
    "inlets": {
        "in": "Noisy signal (e.g., raw ADC)."
    },
    "outlets": {
        "out": "Smoothed average value (Matches input range)."
    },
    "usage": "The 'Golden Node' for hardware. Connect your 'Analog In' here first to eliminate jitter and noise from cheap potentiometers, resulting in rock-solid pitch and volume control."
},
    nodeclass: "MozziRollingAvg",
    description: "Moving average filter.",
    mozzi: {
        rate: "control",
        includes: ["#include <RollingAverage.h>"],
        defaults: {"in":"0"},
        global: function(n,v){ return "RollingAverage<int, 16> "+v+";"; },
        control: function(n,v,i){ v+"_val = "+v+".next((int)"+i.in+");"; },
        audio: function(n,v){ return v+"_out="+v+"_val;"; },
        inlet_rates: {"in":"elastic"},
    },
    rpdnode: {
    "title": "Rolling Avg",
    "inlets": {
        "in": {
            "type": "mozziflow/string",
            "no_text": true,
            "color": "unipolar_16"
        }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "unipolar_16"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'signal/mozzi_automap',
    help: {
    "summary": "Auto-scaling range mapper. Learns input limits dynamically.",
    "inlets": {
        "in": "Raw input signal.",
        "imin": "Initial minimum expected (e.g., 0).",
        "imax": "Initial maximum expected (e.g., 1023).",
        "omin": "Destination minimum.",
        "omax": "Destination maximum."
    },
    "outlets": {
        "out": "Mapped signal within destination range."
    },
    "usage": "Plug-and-play sensor support. It automatically scales whatever range the sensor provides into your destination range. For CH32X035, set imax to 4095."
},
    nodeclass: "MozziAutoMap",
    description: "Auto-scaling mapper.",
    mozzi: {
        includes: ["#include <AutoMap.h>"],
        defaults: {"in":"0","imin":"0","imax":"1023","omin":"0","omax":"255"},
        global: function(n,v){ 
            var getVal = function(a, d) {
                if (n.nodeinletvalue && n.nodeinletvalue[a]) return n.nodeinletvalue[a][1];
                return d;
            };
            var imin = getVal('imin', '0');
            var imax = getVal('imax', '1023');
            var omin = getVal('omin', '0');
            var omax = getVal('omax', '255');
            return "AutoMap "+v+" ("+imin+","+imax+","+omin+","+omax+");"; 
        },
        audio: function(n,v,i){ return v+"_out = "+v+"((int)"+i.in+");"; },
        inlet_rates: {"in":"elastic","imin":"control","imax":"control","omin":"control","omax":"control"},
    },
    rpdnode: {
    "title": "AutoMap",
    "inlets": {
        "in": {
            "type": "mozziflow/string",
            "no_text": true,
            "color": "unipolar_16"
        },
        "imin": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "imax": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "omin": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "omax": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "unipolar_16"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'signal/mozzi_gain',
    help: {
    "summary": "Digital volume control and signal attenuator.",
    "inlets": {
        "in": "Audio or Control signal.",
        "gain": "Scaling factor (0-255)."
    },
    "outlets": {
        "out": "Attenuated signal (Same range as input)."
    },
    "usage": "The most common utility. Use it to adjust the 'depth' of an LFO modulation or the final volume of an oscillator before mixing."
},
    nodeclass: "MozziGain",
    description: "Digital VCA.",
    mozzi: {
        defaults: {"in":"0","gain":"128"},
        audio: function(n,v,i){ return v+"_out = (int)(((long)"+i.in+" * (int)"+i.gain+") >> 8);"; },
        inlet_rates: {"in":"elastic","gain":"control"},
    },
    rpdnode: {
    "title": "Gain",
    "inlets": {
        "in": {
            "type": "mozziflow/string",
            "no_text": true
        },
        "gain": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "unipolar_8"
        }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'signal/mozzi_mixer2',
    help: {
    "summary": "Standard 2-channel signal summer (Mixer).",
    "inlets": {
        "ch1": "Input channel 1.",
        "ch2": "Input channel 2."
    },
    "outlets": {
        "out": "Combined signal (Sum of inputs)."
    },
    "usage": "Layer two different sounds together. Warning: Summing two full-volume signals may cause digital clipping; reduce individual gains if distortion occurs."
},
    nodeclass: "MozziMixer2",
    description: "2-channel mixer.",
    mozzi: {
        defaults: {"ch1":"0","ch2":"0"},
        audio: function(n,v,i){ return v+"_out = (int)"+i.ch1+" + (int)"+i.ch2+";"; },
        inlet_rates: {"ch1":"elastic","ch2":"elastic"},
    },
    rpdnode: {
    "title": "Mixer 2",
    "inlets": {
        "ch1": {
            "type": "mozziflow/string",
            "no_text": true
        },
        "ch2": {
            "type": "mozziflow/string",
            "no_text": true
        }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'signal/toggle',
    help: {
    "summary": "Latching logic switch (Flip-Flop).",
    "inlets": {
        "trig": "Input pulse (trigger)."
    },
    "outlets": {
        "out": "Latching state: 0 or 255."
    },
    "usage": "Convert a momentary push-button into a toggle switch. Press once to turn an effect ON, press again to turn it OFF."
},
    nodeclass: "ArduinoToggle",
    description: "Latching trigger switch.",
    mozzi: {
        rate: "control",
        defaults: {"trig":"0"},
        global: function(n,v){ return "bool "+v+"_s=0; bool "+v+"_l=0;"; },
        audio: function(n,v){ return ""; },
    },
    rpdnode: {
    "title": "Toggle",
    "inlets": {
        "trig": {
            "type": "mozziflow/string",
            "no_text": true,
            "color": "logic"
        }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "logic"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'signal/router',
    help: {
    "summary": "1-to-8 Control Signal Dispatcher.",
    "inlets": {
        "in": "Data signal to route.",
        "idx": "Destination selector (index 0 to 7)."
    },
    "outlets": {
        "out0-out7": "Individual output channels (Matches input value)."
    },
    "usage": "Smart control allocation. Use one hardware knob to control up to 8 different parameters by switching the 'idx' value (e.g., via a selector switch or another sequencer)."
},
    nodeclass: "ArduinoRouter",
    description: "Control signal router.",
    mozzi: {
        rate: "control",
        defaults: {"in":"0","idx":"0"},
        global: function(n,v){ return "int "+v+"_v[8]={0};"; },
        control: function(n,v,i){ return "int "+v+"_idx=(int)"+i.idx+"; if("+v+"_idx<8) "+v+"_v["+v+"_idx]=(int)"+i.in+";\n\t"+v+"_out0="+v+"_v[0]; "+v+"_out1="+v+"_v[1]; "+v+"_out2="+v+"_v[2]; "+v+"_out3="+v+"_v[3]; "+v+"_out4="+v+"_v[4]; "+v+"_out5="+v+"_v[5]; "+v+"_out6="+v+"_v[6]; "+v+"_out7="+v+"_v[7];"; },
        audio: function(n,v){ return ""; },
        inlet_rates: {"in":"elastic","sel":"control"},
    },
    rpdnode: {
    "title": "Router",
    "inlets": {
        "in": {
            "type": "mozziflow/string",
            "no_text": true
        },
        "idx": {
            "type": "mozziflow/string",
            "color": "logic"
        }
    },
    "outlets": {
        "out0": { "type": "mozziflow/string" },
        "out1": { "type": "mozziflow/string" },
        "out2": { "type": "mozziflow/string" },
        "out3": { "type": "mozziflow/string" },
        "out4": { "type": "mozziflow/string" },
        "out5": { "type": "mozziflow/string" },
        "out6": { "type": "mozziflow/string" },
        "out7": { "type": "mozziflow/string" }
    }
}
});

NodeLibrary.push({
    nodetype: 'signal/mozzi_adsr',
    help: {
    "summary": "Classic 4-stage instrument envelope (Attack, Decay, Sustain, Release) with adjustable levels and times.",
    "inlets": {
        "trig": "Gate input (High = Note On, Low = Note Off).",
        "rst": "Hard Reset (High = Always start from 0, Low = Legato/Rising).",
        "att": "Attack time (ms).",
        "lev": "Attack peak level (0-255).",
        "dec": "Decay time (ms).",
        "sus": "Sustain level (0-255).",
        "rel": "Release time (ms)."
    },
    "outlets": {
        "out": "Dynamic control signal (0-255).",
        "act": "Active status: 255 while playing, 0 when idle."
    },
    "usage": "Connect 'out' to a Gain node. Use 'act' to trigger other events when the sound ends. 'rst' allows snappy re-triggering of notes."
},
    nodeclass: "MozziADSR",
    description: "Full ADSR Envelope.",
    mozzi: {
        rate: "audio",
        includes: ["#include <ADSR.h>"],
        defaults: {"trig":"0","rst":"0","att":"10","lev":"255","dec":"100","sus":"128","rel":"50"},
        global: function(n,v){ return "ADSR<CONTROL_RATE, AUDIO_RATE> "+v+"; bool "+v+"_l=0;"; },
        setup: function(n,v,i){ return ""; },
        control: function(n,v,i){ 
            return "bool "+v+"_tr=(int)"+i.trig+">0;\n\t" +
                   "if("+v+"_tr && !"+v+"_l){ "+v+".noteOn((int)"+i.rst+">0); } " +
                   "else if(!"+v+"_tr && "+v+"_l){ "+v+".noteOff(); }\n\t" +
                   v+"_l="+v+"_tr;\n\t" +
                   v+".setADLevels((uint8_t)"+i.lev+", (uint8_t)"+i.sus+");\n\t" +
                   v+".setTimes((unsigned int)"+i.att+", (unsigned int)"+i.dec+", 65535, (unsigned int)"+i.rel+");\n\t" + 
                   v+".update();\n\t" +
                   v+"_act = "+v+".playing() ? 255 : 0;"; 
        },
        audio: function(n,v){ return v+"_out = "+v+".next();"; },
    },
    rpdnode: {
    "title": "ADSR",
    "inlets": {
        "trig": { "type": "mozziflow/string", "color": "logic" },
        "rst": { "type": "mozziflow/string", "color": "logic" },
        "att": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "lev": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_8" },
        "dec": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "sus": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_8" },
        "rel": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" }
    },
    "outlets": {
        "out": { "type": "mozziflow/string", "color": "unipolar_8" },
        "act": { "type": "mozziflow/string", "color": "logic" }
    }
}
});

NodeLibrary.push({
    nodetype: 'signal/mozzi_line',
    help: {
    "summary": "High-precision linear value ramp generator.",
    "inlets": {
        "trig": "Start signal.",
        "start": "Starting value.",
        "end": "Destination value."
    },
    "outlets": {
        "out": "The current value during the ramp."
    },
    "usage": "Perfect for creating smooth pitch slides (glissando) or very long, automated filter sweeps that span several seconds."
},
    nodeclass: "MozziLine",
    description: "Linear value ramp generator.",
    mozzi: {
        includes: ["#include <Line.h>"],
        defaults: {"trig":"0","start":"0","end":"255","steps":"1000"},
        global: function(n,v){ return "Line<int> "+v+"; bool "+v+"_l=0;"; },
        control: function(n,v,i){ return "if((int)"+i.trig+">0 && !"+v+"_l){ "+v+".set((int)"+i.start+",(int)"+i.end+",(int)"+i.steps+"); "+v+"_l=1; } else if((int)"+i.trig+"==0) "+v+"_l=0;"; },
        audio: function(n,v,i){ return v+"_out = "+v+".next();"; },
        inlet_rates: {"trig":"control","start":"control","end":"control","steps":"control"},
    },
    rpdnode: {
    "title": "Line",
    "inlets": {
        "trig": {
            "type": "mozziflow/string",
            "no_text": true,
            "is_control": true,
            "color": "logic"
        },
        "start": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "bipolar_16"
        },
        "end": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "bipolar_16"
        },
        "steps": {
            "type": "mozziflow/string",
            "default": "1000",
            "is_control": true,
            "color": "unipolar_16"
        }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "unipolar_16"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'signal/mozzi_smooth',
    help: {
    "summary": "Low-pass 'Lag' filter for control signals. Adds inertia to changes.",
    "inlets": {
        "in": "Raw or stepped control signal."
    },
    "outlets": {
        "out": "Smoothed, gliding signal."
    },
    "usage": "The secret to 'Analog' feeling. Use it to add **Portamento** to sequencer notes or to smooth out the jumps between different preset values."
},
    nodeclass: "MozziSmooth",
    description: "Softens rapid changes.",
    mozzi: {
        rate: "control",
        includes: ["#include <Smooth.h>"],
        defaults: {"in":"0","smooth":"0.95"},
        global: function(n,v){ return "Smooth<long> "+v+"(0.95f);"; },
        control: function(n,v,i){ 
            return "float "+v+"_sm = (float)"+i.smooth+"; if("+v+"_sm<0.0f)"+v+"_sm=0.0f; if("+v+"_sm>0.99f)"+v+"_sm=0.99f; "+v+".setSmoothness("+v+"_sm);\n\t"+v+"_out = "+v+".next((long)"+i.in+");";
        },
        audio: function(n,v,i){ return ""; },
    },
    rpdnode: {
    "title": "Smooth",
    "inlets": {
        "in": {
            "type": "mozziflow/string",
            "no_text": true,
            "color": "unipolar_16"
        },
        "smooth": {
            "type": "mozziflow/string",
            "default": "0.95",
            "is_control": true,
            "color": "unipolar_8"
        }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "unipolar_16"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'signal/mozzi_metronome',
    help: {
    "summary": "Master rhythmic clock generator.",
    "inlets": {
        "bpm": "Beats Per Minute (Tempo)."
    },
    "outlets": {
        "out": "Gate/Clock signal: 255 (High) for 50% of the beat, 0 (Low) otherwise."
    },
    "usage": "The heartbeat of your patch. Connect it to the 'trig' inlet of any 'Sequencer' or 'ADSR' node to maintain a perfect musical tempo."
},
    nodeclass: "MozziMetronome",
    description: "BPM timing pulse.",
        mozzi: {
            rate: "control",
            includes: ["#include <Metronome.h>"],
            defaults: {"bpm":"120"},
            global: function(n,v){ return "Metronome " + v + ";"; },
            setup: function(n,v){ return v + ".start();"; },
            control: function(n,v,i){ return v+".setBPM((float)"+i.bpm+");\n\t"+v+"_out = "+v+".ready() ? 255 : 0;"; },
        },    rpdnode: {
    "title": "Metronome",
    "inlets": {
        "bpm": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "unipolar_16"
        }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "logic"
        }
    }
}
});


NodeLibrary.push({
    nodetype: 'signal/mozzi_ead',
    help: {
    "summary": "Exponential Attack-Decay (EAD) envelope generator.",
    "inlets": {
        "trig": "Trigger pulse to start the envelope."
    },
    "outlets": {
        "out": "Percussive control signal."
    },
    "usage": "Optimized for **Drum Synthesis**. Uses glitch-free retriggering (starts from current level)."
},
    nodeclass: "MozziEad",
    description: "Exponential Attack-Decay (Control Rate).",
    mozzi: {
        rate: "control",
        includes: ["#include <Ead.h>"],
        defaults: {"trig":"0","att":"10","dec":"200"},
        global: function(n,v){ return "Ead "+v+"(CONTROL_RATE); bool "+v+"_l=0;"; },
        control: function(n,v,i){ 
            return "if((int)"+i.trig+">0 && !"+v+"_l){ " +
                   v+".start((unsigned int)"+i.att+", (unsigned int)"+i.dec+"); " +
                   v+"_l=1; } " +
                   "else if((int)"+i.trig+"==0) "+v+"_l=0;\n\t" +
                   v+"_out = "+v+".next();"; 
        },
        audio: function(n,v){ return ""; },
        inlet_rates: {"trig":"control","att":"control","dec":"control"},
    },
    rpdnode: {
    "title": "Ead Env",
    "inlets": {
        "trig": {
            "type": "mozziflow/string",
            "no_text": true,
            "color": "logic"
        },
        "att": {
            "type": "mozziflow/string",
            "default": "10",
            "is_control": true,
            "color": "unipolar_16"
        },
        "dec": {
            "type": "mozziflow/string",
            "default": "200",
            "is_control": true,
            "color": "unipolar_16"
        }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "unipolar_8"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'signal/mozzi_portamento',
    help: {
    "summary": "Specialized MIDI-style glissando logic for pitch.",
    "inlets": {
        "note": "Target MIDI note number.",
        "time": "Slide duration in milliseconds (ms).",
        "trig": "Signal to start the glide to the new note."
    },
    "outlets": {
        "out": "Gliding frequency stream."
    },
    "usage": "Create classic monophonic lead synth behavior where notes 'slide' from one to another. Adjust 'time' for the speed of the slide. Connect 'out' to an oscillator frequency inlet."
},
    nodeclass: "MozziPortamento",
    description: "MIDI note glide.",
    mozzi: {
        rate: "control",
        includes: ["#include <Portamento.h>"],
        defaults: {"note":"60","time":"200","trig":"0"},
        global: function(n,v){ return "Portamento<CONTROL_RATE> "+v+"; bool "+v+"_l=0;"; },
        control: function(n,v,i){ 
            return v+".setTime((unsigned int)"+i.time+");\n\t" +
                   "if((int)"+i.trig+">0 && !"+v+"_l){ "+v+".start((uint8_t)"+i.note+"); "+v+"_l=1; } else if((int)"+i.trig+"==0) "+v+"_l=0;\n\t" +
                   v+"_out = "+v+".next();";
        },
        audio: function(n,v,i){ return ""; },
        inlet_rates: {"note":"control","trig":"control"},
    },
    rpdnode: {
    "title": "Portamento",
    "inlets": {
        "note": {
            "type": "mozziflow/string",
            "color": "unipolar_8"
        },
        "time": {
            "type": "mozziflow/string",
            "is_control": true,
            "color": "unipolar_16"
        },
        "trig": {
            "type": "mozziflow/string",
            "no_text": true,
            "color": "logic"
        }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "unipolar_16"
        }
    }
}
});
NodeLibrary.push({
    nodetype: 'signal/mozzi_sequencer',
    help: {
    "summary": "8-step programmable voltage sequencer.",
    "inlets": {
        "trig": "Clock pulse to advance to the next step.",
        "steps": "Active length of the sequence (1 to 8).",
        "s0-s7": "Individual values for each of the 8 steps."
    },
    "outlets": {
        "out": "Value of the active step.",
        "index": "Current step number (0-7)."
    },
    "usage": "The primary melodic engine. Use it to cycle through 8 notes or volumes. Connect 'index' to a 'OneHot' node to drive status LEDs on your hardware."
},
    nodeclass: "MozziSequencer",
    description: "8-step sequencer with variable length.",
    mozzi: {
        rate: "control",
        defaults: {"trig":"0","steps":"8","s0":"0","s1":"0","s2":"0","s3":"0","s4":"0","s5":"0","s6":"0","s7":"0"},
        global: function(n,v){ return "int "+v+"_s[8]={0}; byte "+v+"_i=0; bool "+v+"_l=0;"; },
        control: function(n,v,i){ 
            var s="int "+v+"_len=(int)"+i.steps+"; if("+v+"_len<1)"+v+"_len=1; if("+v+"_len>8)"+v+"_len=8;\n\t";
            for(var j=0;j<8;j++) s+=v+"_s["+j+"]=(int)"+i['s'+j]+";\n\t"; 
            s += "if("+v+"_i >= "+v+"_len) "+v+"_i=0;\n\t";
            s += "if((int)"+i.trig+">0 && !"+v+"_l){ "+v+"_i++; if("+v+"_i >= "+v+"_len) "+v+"_i=0; "+v+"_l=1; }";
            s += "else if((int)"+i.trig+"==0) "+v+"_l=0;\n\t";
            s += v+"_out="+v+"_s["+v+"_i]; "+v+"_index="+v+"_i;"; 
            return s;
        },
        audio: function(n,v){ return ""; },
        inlet_rates: {"trig":"control"},
    },
    rpdnode: {
    "title": "Sequencer (8)",
    "inlets": {
        "trig": {
            "type": "mozziflow/string",
            "no_text": true,
            "is_control": true,
            "color": "logic"
        },
        "steps": {
            "type": "mozziflow/string",
            "default": "8",
            "is_control": true,
            "color": "unipolar_16"
        },
        "s0": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s1": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s2": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s3": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s4": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s5": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s6": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s7": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "unipolar_16"
        },
        "index": {
            "type": "mozziflow/string",
            "color": "unipolar_16"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'signal/mozzi_sequencer16',
    help: {
    "summary": "16-step programmable voltage sequencer.",
    "inlets": {
        "trig": "Clock pulse.",
        "steps": "Sequence length (1-16).",
        "s0-s15": "Individual step values."
    },
    "outlets": {
        "out": "Active value.",
        "index": "Step index (0-15)."
    },
    "usage": "Standard for 4/4 drum patterns and basslines. Offers double the melodic variety of the 8-step version."
},
    nodeclass: "MozziSequencer16",
    description: "16-step sequencer.",
    mozzi: {
        rate: "control",
        defaults: {"trig":"0","steps":"16","s0":"0","s1":"0","s2":"0","s3":"0","s4":"0","s5":"0","s6":"0","s7":"0","s8":"0","s9":"0","s10":"0","s11":"0","s12":"0","s13":"0","s14":"0","s15":"0"},
        global: function(n,v){ return "int "+v+"_s[16]={0}; byte "+v+"_i=0; bool "+v+"_l=0;"; },
        control: function(n,v,i){ 
            var s="int "+v+"_len=(int)"+i.steps+"; if("+v+"_len<1)"+v+"_len=1; if("+v+"_len>16)"+v+"_len=16;\n\t";
            for(var j=0;j<16;j++) s+=v+"_s["+j+"]=(int)"+i['s'+j]+";\n\t"; 
            s += "if("+v+"_i >= "+v+"_len) "+v+"_i=0;\n\t";
            s += "if((int)"+i.trig+">0 && !"+v+"_l){ "+v+"_i++; if("+v+"_i >= "+v+"_len) "+v+"_i=0; "+v+"_l=1; }";
            s += "else if((int)"+i.trig+"==0) "+v+"_l=0;\n\t";
            s += v+"_out="+v+"_s["+v+"_i]; "+v+"_index="+v+"_i;"; 
            return s;
        },
        audio: function(n,v){ return ""; },
        inlet_rates: {"trig":"control"},
    },
    rpdnode: {
    "title": "Sequencer (16)",
    "inlets": {
        "trig": { "type": "mozziflow/string", "no_text": true, "is_control": true, "color": "logic" },
        "steps": { "type": "mozziflow/string", "default": "16", "is_control": true, "color": "unipolar_16" },
        "s0": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s1": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s2": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s3": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s4": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s5": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s6": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s7": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s8": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s9": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s10": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s11": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s12": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s13": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s14": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s15": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "unipolar_16"
        },
        "index": {
            "type": "mozziflow/string",
            "color": "unipolar_16"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'signal/mozzi_sequencer24',
    help: {
    "summary": "24-step programmable voltage sequencer.",
    "inlets": {
        "trig": "Clock pulse.",
        "steps": "Active length (1-24).",
        "s0-s23": "Step values."
    },
    "outlets": {
        "out": "Active value.",
        "index": "Current step (0-23)."
    },
    "usage": "Ideal for triple-meter music (3/4, 6/8) or longer, complex melodic phrases."
},
    nodeclass: "MozziSequencer24",
    description: "24-step sequencer.",
    mozzi: {
        rate: "control",
        defaults: {"trig":"0","steps":"24","s0":"0","s1":"0","s2":"0","s3":"0","s4":"0","s5":"0","s6":"0","s7":"0","s8":"0","s9":"0","s10":"0","s11":"0","s12":"0","s13":"0","s14":"0","s15":"0","s16":"0","s17":"0","s18":"0","s19":"0","s20":"0","s21":"0","s22":"0","s23":"0"},
        global: function(n,v){ return "int "+v+"_s[24]={0}; byte "+v+"_i=0; bool "+v+"_l=0;"; },
        control: function(n,v,i){ 
            var s="int "+v+"_len=(int)"+i.steps+"; if("+v+"_len<1)"+v+"_len=1; if("+v+"_len>24)"+v+"_len=24;\n\t";
            for(var j=0;j<24;j++) s+=v+"_s["+j+"]=(int)"+i['s'+j]+";\n\t"; 
            s += "if("+v+"_i >= "+v+"_len) "+v+"_i=0;\n\t";
            s += "if((int)"+i.trig+">0 && !"+v+"_l){ "+v+"_i++; if("+v+"_i >= "+v+"_len) "+v+"_i=0; "+v+"_l=1; }";
            s += "else if((int)"+i.trig+"==0) "+v+"_l=0;\n\t";
            s += v+"_out="+v+"_s["+v+"_i]; "+v+"_index="+v+"_i;"; 
            return s;
        },
        audio: function(n,v){ return ""; },
        inlet_rates: {"trig":"control"},
    },
    rpdnode: {
    "title": "Sequencer (24)",
    "inlets": {
        "trig": {
            "type": "mozziflow/string",
            "no_text": true,
            "is_control": true,
            "color": "logic"
        },
        "steps": {
            "type": "mozziflow/string",
            "default": "24",
            "is_control": true,
            "color": "unipolar_16"
        },
        "s0": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s1": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s2": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s3": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s4": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s5": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s6": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s7": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s8": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s9": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s10": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s11": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s12": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s13": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s14": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s15": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s16": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s17": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s18": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s19": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s20": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s21": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s22": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s23": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "unipolar_16"
        },
        "index": {
            "type": "mozziflow/string",
            "color": "unipolar_16"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'signal/mozzi_sequencer32',
    help: {
    "summary": "32-step programmable voltage sequencer.",
    "inlets": {
        "trig": "Clock pulse.",
        "steps": "Active length (1-32).",
        "s0-s31": "Step values."
    },
    "outlets": {
        "out": "Active value.",
        "index": "Current step (0-31)."
    },
    "usage": "Enables long, evolving musical phrases spanning multiple bars."
},
    nodeclass: "MozziSequencer32",
    description: "32-step sequencer.",
    mozzi: {
        rate: "control",
        defaults: {"trig":"0","steps":"32","s0":"0","s1":"0","s2":"0","s3":"0","s4":"0","s5":"0","s6":"0","s7":"0","s8":"0","s9":"0","s10":"0","s11":"0","s12":"0","s13":"0","s14":"0","s15":"0","s16":"0","s17":"0","s18":"0","s19":"0","s20":"0","s21":"0","s22":"0","s23":"0","s24":"0","s25":"0","s26":"0","s27":"0","s28":"0","s29":"0","s30":"0","s31":"0"},
        global: function(n,v){ return "int "+v+"_s[32]={0}; byte "+v+"_i=0; bool "+v+"_l=0;"; },
        control: function(n,v,i){ 
            var s="int "+v+"_len=(int)"+i.steps+"; if("+v+"_len<1)"+v+"_len=1; if("+v+"_len>32)"+v+"_len=32;\n\t";
            for(var j=0;j<32;j++) s+=v+"_s["+j+"]=(int)"+i['s'+j]+";\n\t"; 
            s += "if("+v+"_i >= "+v+"_len) "+v+"_i=0;\n\t";
            s += "if((int)"+i.trig+">0 && !"+v+"_l){ "+v+"_i++; if("+v+"_i >= "+v+"_len) "+v+"_i=0; "+v+"_l=1; }";
            s += "else if((int)"+i.trig+"==0) "+v+"_l=0;\n\t";
            s += v+"_out="+v+"_s["+v+"_i]; "+v+"_index="+v+"_i;"; 
            return s;
        },
        audio: function(n,v){ return ""; },
        inlet_rates: {"trig":"control"},
    },
    rpdnode: {
    "title": "Sequencer (32)",
    "inlets": {
        "trig": { "type": "mozziflow/string", "no_text": true, "is_control": true, "color": "logic" },
        "steps": { "type": "mozziflow/string", "default": "32", "is_control": true, "color": "unipolar_16" },
        "s0": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s1": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s2": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s3": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s4": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s5": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s6": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s7": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s8": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s9": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s10": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s11": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s12": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s13": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s14": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s15": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s16": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s17": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s18": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s19": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s20": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s21": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s22": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s23": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s24": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s25": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s26": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s27": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s28": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s29": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s30": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s31": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "unipolar_16"
        },
        "index": {
            "type": "mozziflow/string",
            "color": "unipolar_16"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'signal/mozzi_sequencer32',
    help: {
    "summary": "32-step programmable voltage sequencer.",
    "inlets": {
        "trig": "Clock pulse.",
        "steps": "Active length (1-32).",
        "s0-s31": "Step values."
    },
    "outlets": {
        "out": "Active value.",
        "index": "Current step (0-31)."
    },
    "usage": "Enables long, evolving musical phrases spanning multiple bars."
},
    nodeclass: "MozziSequencer32",
    description: "32-step sequencer.",
    mozzi: {
        rate: "control",
        defaults: {"trig":"0","steps":"32","s0":"0","s1":"0","s2":"0","s3":"0","s4":"0","s5":"0","s6":"0","s7":"0","s8":"0","s9":"0","s10":"0","s11":"0","s12":"0","s13":"0","s14":"0","s15":"0","s16":"0","s17":"0","s18":"0","s19":"0","s20":"0","s21":"0","s22":"0","s23":"0","s24":"0","s25":"0","s26":"0","s27":"0","s28":"0","s29":"0","s30":"0","s31":"0"},
        global: function(n,v){ return "int "+v+"_s[32]={0}; byte "+v+"_i=0; bool "+v+"_l=0;"; },
        control: function(n,v,i){ 
            var s="int "+v+"_len=(int)"+i.steps+"; if("+v+"_len<1)"+v+"_len=1; if("+v+"_len>32)"+v+"_len=32;\n\t";
            for(var j=0;j<32;j++) s+=v+"_s["+j+"]=(int)"+i['s'+j]+";\n\t"; 
            s += "if("+v+"_i >= "+v+"_len) "+v+"_i=0;\n\t";
            s += "if((int)"+i.trig+">0 && !"+v+"_l){ "+v+"_i++; if("+v+"_i >= "+v+"_len) "+v+"_i=0; "+v+"_l=1; }";
            s += "else if((int)"+i.trig+"==0) "+v+"_l=0;\n\t";
            s += v+"_out="+v+"_s["+v+"_i]; "+v+"_index="+v+"_i;"; 
            return s;
        },
        audio: function(n,v){ return ""; },
        inlet_rates: {"trig":"control"},
    },
    rpdnode: {
    "title": "Sequencer (32)",
    "inlets": {
        "trig": { "type": "mozziflow/string", "no_text": true, "is_control": true, "color": "logic" },
        "steps": { "type": "mozziflow/string", "default": "32", "is_control": true, "color": "unipolar_16" },
        "s0": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s1": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s2": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s3": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s4": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s5": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s6": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s7": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s8": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s9": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s10": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s11": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s12": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s13": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s14": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s15": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s16": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s17": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s18": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s19": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s20": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s21": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s22": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s23": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s24": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s25": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s26": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s27": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s28": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s29": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s30": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" },
        "s31": { "type": "mozziflow/string", "is_control": true, "color": "unipolar_16" }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "unipolar_16"
        },
        "index": {
            "type": "mozziflow/string",
            "color": "unipolar_16"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'signal/mozzi_quantizer',
    help: {
    "summary": "Musical scale 'Auto-Tune' logic. Forces voltages to legal notes.",
    "inlets": {
        "in": "Raw voltage or frequency value."
    },
    "outlets": {
        "out": "Scale-corrected MIDI Note (0-127)."
    },
    "usage": "Ensuring musicality. Connect a random voltage or a manual knob here to make sure you are always playing 'in key' with your song."
},
    nodeclass: "MozziQuantizer",
    description: "Chromatic quantizer.",
    mozzi: {
        defaults: {"in":"0"},
        global: function(n,v){ return "int "+v+"_sc[]={0,2,4,5,7,9,11,12};"; },
        audio: function(n,v,i){ return "int "+v+"_r=(int)abs("+i.in+")/85; "+v+"_out="+v+"_sc["+v+"_r%7]+(("+v+"_r/7)*12)+48;"; },
        inlet_rates: {"in":"elastic"},
    },
    rpdnode: {
    "title": "Quantizer",
    "inlets": {
        "in": {
            "type": "mozziflow/string",
            "no_text": true,
            "color": "unipolar_16"
        }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "unipolar_8"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'signal/mozzi_sh',
    help: {
    "summary": "Sample and Hold (S&H) unit for capturing signals.",
    "inlets": {
        "in": "Signal to be sampled (e.g., Noise).",
        "trig": "Clock pulse to trigger the sample."
    },
    "outlets": {
        "out": "The captured and held value (Matches input)."
    },
    "usage": "Create the classic 'Random Computer' sound. By sampling 'Noise' at a rhythmic rate (Metronome), you generate a random but rhythmic melodic sequence."
},
    nodeclass: "MozziSH",
    description: "Sample & Hold unit.",
    mozzi: {
        defaults: {"in":"0","trig":"0"},
        global: function(n,v){ return "int "+v+"_val=0; bool "+v+"_l=0;"; },
        audio: function(n,v,i){ return "if((int)"+i.trig+">0 && !"+v+"_l){"+v+"_val=(int)"+i.in+"; "+v+"_l=1;}"+"else if((int)"+i.trig+"==0)"+v+"_l=0;\n\t"+v+"_out="+v+"_val;"; },
    },
    rpdnode: {
    "title": "S&H",
    "inlets": {
        "in": {
            "type": "mozziflow/string",
            "no_text": true
        },
        "trig": {
            "type": "mozziflow/string",
            "no_text": true,
            "color": "logic"
        }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string"
        }
    }
}
});

NodeLibrary.push({
    nodetype: 'signal/counter',
    help: {
    "summary": "Logic accumulator for counting events.",
    "inlets": {
        "up": "Increment pulse.",
        "down": "Decrement pulse.",
        "reset": "Return to zero.",
        "min": "Lower limit.",
        "max": "Upper limit."
    },
    "outlets": {
        "out": "Current count value (Integer)."
    },
    "usage": "Track sequencer positions, button presses, or switch between different sound presets."
},
    nodeclass: "ArduinoCounter",
    description: "Value counter.",
    mozzi: {
        rate: "control",
        defaults: {"up":"0","down":"0"},
        global: function(n,v){ return "int "+v+"_v=0; bool "+v+"_lU=0; bool "+v+"_lD=0;"; },
        control: function(n,v,i){ return "if((int)"+i.up+">0 && !"+v+"_lU){"+v+"_v++;"+v+"_lU=1;}"+"else if((int)"+i.up+"==0)"+v+"_lU=0;\n\tif((int)"+i.down+">0 && !"+v+"_lD){"+v+"_v--;"+v+"_lD=1;}"+"else if((int)"+i.down+"==0)"+v+"_lD=0;\n\t"+v+"_out="+v+"_v;"; },
        audio: function(n,v){ return ""; },
        inlet_rates: {"up":"control","down":"control"},
    },
    rpdnode: {
    "title": "Counter",
    "inlets": {
        "up": { "type": "mozziflow/string", "no_text": true, "color": "logic" },
        "down": { "type": "mozziflow/string", "no_text": true, "color": "logic" },
        "reset": { "type": "mozziflow/string", "no_text": true, "color": "logic" },
        "min": { "type": "mozziflow/string", "color": "unipolar_16" },
        "max": { "type": "mozziflow/string", "color": "unipolar_16" }
    },
    "outlets": {
        "out": { "type": "mozziflow/string", "color": "unipolar_16" }
    }
}
});

NodeLibrary.push({
    nodetype: 'signal/arduino_7seg',
    help: {
    "summary": "Logic decoder for 4-digit 7-segment hardware displays.",
    "inlets": {
        "val": "Integer number to display."
    },
    "outlets": {
        "d0-d3": "Encoded segment bytes (0-255)."
    },
    "usage": "Provides visual feedback on physical hardware. Connect these outputs to a 'Shift 595' node to drive a physical LED display module."
},
    nodeclass: "Arduino7Seg",
    description: "7-Seg Driver.",
    mozzi: {
        rate: "control",
        defaults: {"val":"0"},
        global: function(n,v){ return "uint8_t "+v+"_o[4]; const uint8_t "+v+"_m[]={0x3F,0x06,0x5B,0x4F,0x66,0x6D,0x7D,0x07,0x7F,0x6F};"; },
        control: function(n,v,i){ return "long "+v+"_t=(long)"+i.val+"; for(int i=0;i<4;i++){ "+v+"_o[i]="+v+"_m["+v+"_t%10];"+v+"_t/=10;}\n\t"+v+"_d0="+v+"_o[0]; "+v+"_d1="+v+"_o[1]; "+v+"_d2="+v+"_o[2]; "+v+"_d3="+v+"_o[3];"; },
        audio: function(n,v){ return ""; },
        inlet_rates: {"val":"control"},
    },
    rpdnode: {
    "title": "7-Seg Driver",
    "inlets": {
        "val": {
            "type": "mozziflow/string",
            "no_text": true,
            "color": "unipolar_16"
        }
    },
    "outlets": {
        "d0": { "type": "mozziflow/string", "color": "logic" },
        "d1": { "type": "mozziflow/string", "color": "logic" },
        "d2": { "type": "mozziflow/string", "color": "logic" },
        "d3": { "type": "mozziflow/string", "color": "logic" }
    }
}
});

NodeLibrary.push({
    nodetype: 'signal/onehot',
    help: {
    "summary": "Binary-to-Position 'One-Hot' decoder.",
    "inlets": {
        "in": "Numeric index (0-7)."
    },
    "outlets": {
        "out": "Bitmask (Integer)."
    },
    "usage": "Lighting current-step LEDs. If your sequencer is on step 3, this node outputs the binary for '00001000', lighting only the 4th LED in a shift register."
},
    nodeclass: "ArduinoOneHot",
    description: "One-hot bit encoder.",
    mozzi: {
        rate: "control",
        defaults: {"in":"0"},
        control: function(n,v,i){ return v+"_out = 1 << ((int)"+i.in+" & 31);"; },
        audio: function(n,v){ return ""; },
        inlet_rates: {"in":"control"},
    },
    rpdnode: {
    "title": "Index to Bit",
    "inlets": {
        "in": {
            "type": "mozziflow/string",
            "no_text": true,
            "color": "logic"
        }
    },
    "outlets": {
        "out": {
            "type": "mozziflow/string",
            "color": "logic"
        }
    }
}
});

